/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AclByPackagesElementModel
 */
export interface AclByPackagesElementModel {
    /**
     * package name
     * @type {string}
     * @memberof AclByPackagesElementModel
     */
    name?: string;
    /**
     * last ACL update date
     * @type {Date}
     * @memberof AclByPackagesElementModel
     */
    updated?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof AclByPackagesElementModel
     */
    members?: Array<string>;
}

/**
 * Check if a given object implements the AclByPackagesElementModel interface.
 */
export function instanceOfAclByPackagesElementModel(value: object): value is AclByPackagesElementModel {
    return true;
}

export function AclByPackagesElementModelFromJSON(json: any): AclByPackagesElementModel {
    return AclByPackagesElementModelFromJSONTyped(json, false);
}

export function AclByPackagesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AclByPackagesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'members': json['members'] == null ? undefined : json['members'],
    };
}

export function AclByPackagesElementModelToJSON(value?: AclByPackagesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'updated': value['updated'] == null ? undefined : ((value['updated']).toISOString()),
        'members': value['members'],
    };
}

