/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AclMaintainerGroupsElementModel } from './AclMaintainerGroupsElementModel';
import {
    AclMaintainerGroupsElementModelFromJSON,
    AclMaintainerGroupsElementModelFromJSONTyped,
    AclMaintainerGroupsElementModelToJSON,
} from './AclMaintainerGroupsElementModel';

/**
 * 
 * @export
 * @interface AclMaintainerGroupsModel
 */
export interface AclMaintainerGroupsModel {
    /**
     * maintainer's nickname
     * @type {string}
     * @memberof AclMaintainerGroupsModel
     */
    nickname?: string;
    /**
     * branches with maintainer and groups
     * @type {Array<AclMaintainerGroupsElementModel>}
     * @memberof AclMaintainerGroupsModel
     */
    branches?: Array<AclMaintainerGroupsElementModel>;
}

/**
 * Check if a given object implements the AclMaintainerGroupsModel interface.
 */
export function instanceOfAclMaintainerGroupsModel(value: object): value is AclMaintainerGroupsModel {
    return true;
}

export function AclMaintainerGroupsModelFromJSON(json: any): AclMaintainerGroupsModel {
    return AclMaintainerGroupsModelFromJSONTyped(json, false);
}

export function AclMaintainerGroupsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AclMaintainerGroupsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(AclMaintainerGroupsElementModelFromJSON)),
    };
}

export function AclMaintainerGroupsModelToJSON(value?: AclMaintainerGroupsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nickname': value['nickname'],
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(AclMaintainerGroupsElementModelToJSON)),
    };
}

