/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllMaintainersElementModel } from './AllMaintainersElementModel';
import {
    AllMaintainersElementModelFromJSON,
    AllMaintainersElementModelFromJSONTyped,
    AllMaintainersElementModelToJSON,
} from './AllMaintainersElementModel';

/**
 * 
 * @export
 * @interface AllMaintainersModel
 */
export interface AllMaintainersModel {
    /**
     * request arguments
     * @type {object}
     * @memberof AllMaintainersModel
     */
    requestArgs?: object;
    /**
     * number of maintainers found
     * @type {number}
     * @memberof AllMaintainersModel
     */
    length?: number;
    /**
     * maintainers info
     * @type {Array<AllMaintainersElementModel>}
     * @memberof AllMaintainersModel
     */
    maintainers?: Array<AllMaintainersElementModel>;
}

/**
 * Check if a given object implements the AllMaintainersModel interface.
 */
export function instanceOfAllMaintainersModel(value: object): value is AllMaintainersModel {
    return true;
}

export function AllMaintainersModelFromJSON(json: any): AllMaintainersModel {
    return AllMaintainersModelFromJSONTyped(json, false);
}

export function AllMaintainersModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllMaintainersModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'maintainers': json['maintainers'] == null ? undefined : ((json['maintainers'] as Array<any>).map(AllMaintainersElementModelFromJSON)),
    };
}

export function AllMaintainersModelToJSON(value?: AllMaintainersModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'maintainers': value['maintainers'] == null ? undefined : ((value['maintainers'] as Array<any>).map(AllMaintainersElementModelToJSON)),
    };
}

