/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackportHelperBinaryElementModel
 */
export interface BackportHelperBinaryElementModel {
    /**
     * package srpm
     * @type {string}
     * @memberof BackportHelperBinaryElementModel
     */
    srpm?: string;
    /**
     * package name
     * @type {string}
     * @memberof BackportHelperBinaryElementModel
     */
    name?: string;
    /**
     * package epoch
     * @type {number}
     * @memberof BackportHelperBinaryElementModel
     */
    epoch?: number;
    /**
     * package version
     * @type {string}
     * @memberof BackportHelperBinaryElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof BackportHelperBinaryElementModel
     */
    release?: string;
    /**
     * packages arch
     * @type {string}
     * @memberof BackportHelperBinaryElementModel
     */
    arch?: string;
}

/**
 * Check if a given object implements the BackportHelperBinaryElementModel interface.
 */
export function instanceOfBackportHelperBinaryElementModel(value: object): value is BackportHelperBinaryElementModel {
    return true;
}

export function BackportHelperBinaryElementModelFromJSON(json: any): BackportHelperBinaryElementModel {
    return BackportHelperBinaryElementModelFromJSONTyped(json, false);
}

export function BackportHelperBinaryElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackportHelperBinaryElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'srpm': json['srpm'] == null ? undefined : json['srpm'],
        'name': json['name'] == null ? undefined : json['name'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'arch': json['arch'] == null ? undefined : json['arch'],
    };
}

export function BackportHelperBinaryElementModelToJSON(value?: BackportHelperBinaryElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'srpm': value['srpm'],
        'name': value['name'],
        'epoch': value['epoch'],
        'version': value['version'],
        'release': value['release'],
        'arch': value['arch'],
    };
}

