/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BinPackageLogElementModel
 */
export interface BinPackageLogElementModel {
    /**
     * binary package hash
     * @type {string}
     * @memberof BinPackageLogElementModel
     */
    pkgHash?: string;
    /**
     * task id
     * @type {number}
     * @memberof BinPackageLogElementModel
     */
    taskId?: number;
    /**
     * subtask id
     * @type {number}
     * @memberof BinPackageLogElementModel
     */
    subtaskId?: number;
    /**
     * package architecture
     * @type {string}
     * @memberof BinPackageLogElementModel
     */
    subtaskArch?: string;
    /**
     * hash of the log
     * @type {string}
     * @memberof BinPackageLogElementModel
     */
    buildlogHash?: string;
    /**
     * link to the binary package build log
     * @type {string}
     * @memberof BinPackageLogElementModel
     */
    link?: string;
}

/**
 * Check if a given object implements the BinPackageLogElementModel interface.
 */
export function instanceOfBinPackageLogElementModel(value: object): value is BinPackageLogElementModel {
    return true;
}

export function BinPackageLogElementModelFromJSON(json: any): BinPackageLogElementModel {
    return BinPackageLogElementModelFromJSONTyped(json, false);
}

export function BinPackageLogElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinPackageLogElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pkgHash': json['pkg_hash'] == null ? undefined : json['pkg_hash'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'subtaskId': json['subtask_id'] == null ? undefined : json['subtask_id'],
        'subtaskArch': json['subtask_arch'] == null ? undefined : json['subtask_arch'],
        'buildlogHash': json['buildlog_hash'] == null ? undefined : json['buildlog_hash'],
        'link': json['link'] == null ? undefined : json['link'],
    };
}

export function BinPackageLogElementModelToJSON(value?: BinPackageLogElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pkg_hash': value['pkgHash'],
        'task_id': value['taskId'],
        'subtask_id': value['subtaskId'],
        'subtask_arch': value['subtaskArch'],
        'buildlog_hash': value['buildlogHash'],
        'link': value['link'],
    };
}

