/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchTreeTaskModel
 */
export interface BranchTreeTaskModel {
    /**
     * task ID
     * @type {number}
     * @memberof BranchTreeTaskModel
     */
    id?: number;
    /**
     * previous task ID
     * @type {number}
     * @memberof BranchTreeTaskModel
     */
    prev?: number;
    /**
     * task branch name
     * @type {string}
     * @memberof BranchTreeTaskModel
     */
    branch?: string;
    /**
     * task build time
     * @type {string}
     * @memberof BranchTreeTaskModel
     */
    date?: string;
}

/**
 * Check if a given object implements the BranchTreeTaskModel interface.
 */
export function instanceOfBranchTreeTaskModel(value: object): value is BranchTreeTaskModel {
    return true;
}

export function BranchTreeTaskModelFromJSON(json: any): BranchTreeTaskModel {
    return BranchTreeTaskModelFromJSONTyped(json, false);
}

export function BranchTreeTaskModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchTreeTaskModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'prev': json['prev'] == null ? undefined : json['prev'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function BranchTreeTaskModelToJSON(value?: BranchTreeTaskModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'prev': value['prev'],
        'branch': value['branch'],
        'date': value['date'],
    };
}

