/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BugzillaInfoElementModel } from './BugzillaInfoElementModel';
import {
    BugzillaInfoElementModelFromJSON,
    BugzillaInfoElementModelFromJSONTyped,
    BugzillaInfoElementModelToJSON,
} from './BugzillaInfoElementModel';

/**
 * 
 * @export
 * @interface BugzillaInfoModel
 */
export interface BugzillaInfoModel {
    /**
     * request arguments
     * @type {object}
     * @memberof BugzillaInfoModel
     */
    requestArgs?: object;
    /**
     * number of bugs found
     * @type {number}
     * @memberof BugzillaInfoModel
     */
    length?: number;
    /**
     * bugzilla info
     * @type {Array<BugzillaInfoElementModel>}
     * @memberof BugzillaInfoModel
     */
    bugs?: Array<BugzillaInfoElementModel>;
}

/**
 * Check if a given object implements the BugzillaInfoModel interface.
 */
export function instanceOfBugzillaInfoModel(value: object): value is BugzillaInfoModel {
    return true;
}

export function BugzillaInfoModelFromJSON(json: any): BugzillaInfoModel {
    return BugzillaInfoModelFromJSONTyped(json, false);
}

export function BugzillaInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BugzillaInfoModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'bugs': json['bugs'] == null ? undefined : ((json['bugs'] as Array<any>).map(BugzillaInfoElementModelFromJSON)),
    };
}

export function BugzillaInfoModelToJSON(value?: BugzillaInfoModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'bugs': value['bugs'] == null ? undefined : ((value['bugs'] as Array<any>).map(BugzillaInfoElementModelToJSON)),
    };
}

