/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BuildDependencySetPackageModel
 */
export interface BuildDependencySetPackageModel {
    /**
     * package name
     * @type {string}
     * @memberof BuildDependencySetPackageModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof BuildDependencySetPackageModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof BuildDependencySetPackageModel
     */
    release?: string;
    /**
     * package epoch
     * @type {number}
     * @memberof BuildDependencySetPackageModel
     */
    epoch?: number;
    /**
     * binary packages archs
     * @type {Array<string>}
     * @memberof BuildDependencySetPackageModel
     */
    archs?: Array<string>;
    /**
     * binary packages require dependencies
     * @type {Array<string>}
     * @memberof BuildDependencySetPackageModel
     */
    requires?: Array<string>;
}

/**
 * Check if a given object implements the BuildDependencySetPackageModel interface.
 */
export function instanceOfBuildDependencySetPackageModel(value: object): value is BuildDependencySetPackageModel {
    return true;
}

export function BuildDependencySetPackageModelFromJSON(json: any): BuildDependencySetPackageModel {
    return BuildDependencySetPackageModelFromJSONTyped(json, false);
}

export function BuildDependencySetPackageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildDependencySetPackageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'archs': json['archs'] == null ? undefined : json['archs'],
        'requires': json['requires'] == null ? undefined : json['requires'],
    };
}

export function BuildDependencySetPackageModelToJSON(value?: BuildDependencySetPackageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'epoch': value['epoch'],
        'archs': value['archs'],
        'requires': value['requires'],
    };
}

