/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BuildDependencySetAmbiguousProvidesElementModel } from './BuildDependencySetAmbiguousProvidesElementModel';
import {
    BuildDependencySetAmbiguousProvidesElementModelFromJSON,
    BuildDependencySetAmbiguousProvidesElementModelFromJSONTyped,
    BuildDependencySetAmbiguousProvidesElementModelToJSON,
} from './BuildDependencySetAmbiguousProvidesElementModel';

/**
 * 
 * @export
 * @interface BuildDependencySetAmbiguousProvidesModel
 */
export interface BuildDependencySetAmbiguousProvidesModel {
    /**
     * package name
     * @type {string}
     * @memberof BuildDependencySetAmbiguousProvidesModel
     */
    _package?: string;
    /**
     * list of found and resolved ambiguous provides
     * @type {Array<BuildDependencySetAmbiguousProvidesElementModel>}
     * @memberof BuildDependencySetAmbiguousProvidesModel
     */
    ambiguousProvides?: Array<BuildDependencySetAmbiguousProvidesElementModel>;
}

/**
 * Check if a given object implements the BuildDependencySetAmbiguousProvidesModel interface.
 */
export function instanceOfBuildDependencySetAmbiguousProvidesModel(value: object): value is BuildDependencySetAmbiguousProvidesModel {
    return true;
}

export function BuildDependencySetAmbiguousProvidesModelFromJSON(json: any): BuildDependencySetAmbiguousProvidesModel {
    return BuildDependencySetAmbiguousProvidesModelFromJSONTyped(json, false);
}

export function BuildDependencySetAmbiguousProvidesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildDependencySetAmbiguousProvidesModel {
    if (json == null) {
        return json;
    }
    return {
        
        '_package': json['package'] == null ? undefined : json['package'],
        'ambiguousProvides': json['ambiguous_provides'] == null ? undefined : ((json['ambiguous_provides'] as Array<any>).map(BuildDependencySetAmbiguousProvidesElementModelFromJSON)),
    };
}

export function BuildDependencySetAmbiguousProvidesModelToJSON(value?: BuildDependencySetAmbiguousProvidesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'package': value['_package'],
        'ambiguous_provides': value['ambiguousProvides'] == null ? undefined : ((value['ambiguousProvides'] as Array<any>).map(BuildDependencySetAmbiguousProvidesElementModelToJSON)),
    };
}

