/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckImagesOutputPackageModel
 */
export interface CheckImagesOutputPackageModel {
    /**
     * binary package status
     * @type {string}
     * @memberof CheckImagesOutputPackageModel
     */
    status?: string;
    /**
     * subtask id
     * @type {number}
     * @memberof CheckImagesOutputPackageModel
     */
    fromSubtask?: number;
    /**
     * source package name
     * @type {string}
     * @memberof CheckImagesOutputPackageModel
     */
    srcpkgName?: string;
    /**
     * binary package name
     * @type {string}
     * @memberof CheckImagesOutputPackageModel
     */
    binpkgName?: string;
    /**
     * binary package architecture
     * @type {string}
     * @memberof CheckImagesOutputPackageModel
     */
    binpkgArch?: string;
}

/**
 * Check if a given object implements the CheckImagesOutputPackageModel interface.
 */
export function instanceOfCheckImagesOutputPackageModel(value: object): value is CheckImagesOutputPackageModel {
    return true;
}

export function CheckImagesOutputPackageModelFromJSON(json: any): CheckImagesOutputPackageModel {
    return CheckImagesOutputPackageModelFromJSONTyped(json, false);
}

export function CheckImagesOutputPackageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckImagesOutputPackageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'fromSubtask': json['from_subtask'] == null ? undefined : json['from_subtask'],
        'srcpkgName': json['srcpkg_name'] == null ? undefined : json['srcpkg_name'],
        'binpkgName': json['binpkg_name'] == null ? undefined : json['binpkg_name'],
        'binpkgArch': json['binpkg_arch'] == null ? undefined : json['binpkg_arch'],
    };
}

export function CheckImagesOutputPackageModelToJSON(value?: CheckImagesOutputPackageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'from_subtask': value['fromSubtask'],
        'srcpkg_name': value['srcpkgName'],
        'binpkg_name': value['binpkgName'],
        'binpkg_arch': value['binpkgArch'],
    };
}

