/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckImagesOutputPackageModel } from './CheckImagesOutputPackageModel';
import {
    CheckImagesOutputPackageModelFromJSON,
    CheckImagesOutputPackageModelFromJSONTyped,
    CheckImagesOutputPackageModelToJSON,
} from './CheckImagesOutputPackageModel';

/**
 * 
 * @export
 * @interface CheckImagesOutputImageModel
 */
export interface CheckImagesOutputImageModel {
    /**
     * image file
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    file?: string;
    /**
     * image branch
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    branch?: string;
    /**
     * image edition
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    edition?: string;
    /**
     * image flavor
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    flavor?: string;
    /**
     * image platform
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    platform?: string;
    /**
     * image release
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    release?: string;
    /**
     * image major version
     * @type {number}
     * @memberof CheckImagesOutputImageModel
     */
    majorVersion?: number;
    /**
     * image minor version
     * @type {number}
     * @memberof CheckImagesOutputImageModel
     */
    minorVersion?: number;
    /**
     * image sub version
     * @type {number}
     * @memberof CheckImagesOutputImageModel
     */
    subVersion?: number;
    /**
     * image arch
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    arch?: string;
    /**
     * image variant
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    variant?: string;
    /**
     * image type
     * @type {string}
     * @memberof CheckImagesOutputImageModel
     */
    type?: string;
    /**
     * image built date in ISO8601 format
     * @type {Date}
     * @memberof CheckImagesOutputImageModel
     */
    buildtime?: Date;
    /**
     * list of binary packages
     * @type {Array<CheckImagesOutputPackageModel>}
     * @memberof CheckImagesOutputImageModel
     */
    packages?: Array<CheckImagesOutputPackageModel>;
}

/**
 * Check if a given object implements the CheckImagesOutputImageModel interface.
 */
export function instanceOfCheckImagesOutputImageModel(value: object): value is CheckImagesOutputImageModel {
    return true;
}

export function CheckImagesOutputImageModelFromJSON(json: any): CheckImagesOutputImageModel {
    return CheckImagesOutputImageModelFromJSONTyped(json, false);
}

export function CheckImagesOutputImageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckImagesOutputImageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'] == null ? undefined : json['file'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'edition': json['edition'] == null ? undefined : json['edition'],
        'flavor': json['flavor'] == null ? undefined : json['flavor'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'release': json['release'] == null ? undefined : json['release'],
        'majorVersion': json['major_version'] == null ? undefined : json['major_version'],
        'minorVersion': json['minor_version'] == null ? undefined : json['minor_version'],
        'subVersion': json['sub_version'] == null ? undefined : json['sub_version'],
        'arch': json['arch'] == null ? undefined : json['arch'],
        'variant': json['variant'] == null ? undefined : json['variant'],
        'type': json['type'] == null ? undefined : json['type'],
        'buildtime': json['buildtime'] == null ? undefined : (new Date(json['buildtime'])),
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(CheckImagesOutputPackageModelFromJSON)),
    };
}

export function CheckImagesOutputImageModelToJSON(value?: CheckImagesOutputImageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'branch': value['branch'],
        'edition': value['edition'],
        'flavor': value['flavor'],
        'platform': value['platform'],
        'release': value['release'],
        'major_version': value['majorVersion'],
        'minor_version': value['minorVersion'],
        'sub_version': value['subVersion'],
        'arch': value['arch'],
        'variant': value['variant'],
        'type': value['type'],
        'buildtime': value['buildtime'] == null ? undefined : ((value['buildtime']).toISOString()),
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(CheckImagesOutputPackageModelToJSON)),
    };
}

