/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckImagesInputFilterModel } from './CheckImagesInputFilterModel';
import {
    CheckImagesInputFilterModelFromJSON,
    CheckImagesInputFilterModelFromJSONTyped,
    CheckImagesInputFilterModelToJSON,
} from './CheckImagesInputFilterModel';

/**
 * 
 * @export
 * @interface CheckImagesInputModel
 */
export interface CheckImagesInputModel {
    /**
     * task id
     * @type {number}
     * @memberof CheckImagesInputModel
     */
    taskId?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CheckImagesInputModel
     */
    binpkgsNames?: Array<string>;
    /**
     * list of filters
     * @type {Array<CheckImagesInputFilterModel>}
     * @memberof CheckImagesInputModel
     */
    filters?: Array<CheckImagesInputFilterModel>;
}

/**
 * Check if a given object implements the CheckImagesInputModel interface.
 */
export function instanceOfCheckImagesInputModel(value: object): value is CheckImagesInputModel {
    return true;
}

export function CheckImagesInputModelFromJSON(json: any): CheckImagesInputModel {
    return CheckImagesInputModelFromJSONTyped(json, false);
}

export function CheckImagesInputModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckImagesInputModel {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'binpkgsNames': json['binpkgs_names'] == null ? undefined : json['binpkgs_names'],
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(CheckImagesInputFilterModelFromJSON)),
    };
}

export function CheckImagesInputModelToJSON(value?: CheckImagesInputModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task_id': value['taskId'],
        'binpkgs_names': value['binpkgsNames'],
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(CheckImagesInputFilterModelToJSON)),
    };
}

