/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DependenciesPackageDependenciesElementModel } from './DependenciesPackageDependenciesElementModel';
import {
    DependenciesPackageDependenciesElementModelFromJSON,
    DependenciesPackageDependenciesElementModelFromJSONTyped,
    DependenciesPackageDependenciesElementModelToJSON,
} from './DependenciesPackageDependenciesElementModel';

/**
 * 
 * @export
 * @interface DependenciesPackageDependenciesModel
 */
export interface DependenciesPackageDependenciesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof DependenciesPackageDependenciesModel
     */
    requestArgs?: object;
    /**
     * number of dependencies found
     * @type {number}
     * @memberof DependenciesPackageDependenciesModel
     */
    length?: number;
    /**
     * package dependencies list
     * @type {Array<DependenciesPackageDependenciesElementModel>}
     * @memberof DependenciesPackageDependenciesModel
     */
    dependencies?: Array<DependenciesPackageDependenciesElementModel>;
}

/**
 * Check if a given object implements the DependenciesPackageDependenciesModel interface.
 */
export function instanceOfDependenciesPackageDependenciesModel(value: object): value is DependenciesPackageDependenciesModel {
    return true;
}

export function DependenciesPackageDependenciesModelFromJSON(json: any): DependenciesPackageDependenciesModel {
    return DependenciesPackageDependenciesModelFromJSONTyped(json, false);
}

export function DependenciesPackageDependenciesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DependenciesPackageDependenciesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'dependencies': json['dependencies'] == null ? undefined : ((json['dependencies'] as Array<any>).map(DependenciesPackageDependenciesElementModelFromJSON)),
    };
}

export function DependenciesPackageDependenciesModelToJSON(value?: DependenciesPackageDependenciesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'dependencies': value['dependencies'] == null ? undefined : ((value['dependencies'] as Array<any>).map(DependenciesPackageDependenciesElementModelToJSON)),
    };
}

