/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DependenciesAllPackagasetsElementModel } from './DependenciesAllPackagasetsElementModel';
import {
    DependenciesAllPackagasetsElementModelFromJSON,
    DependenciesAllPackagasetsElementModelFromJSONTyped,
    DependenciesAllPackagasetsElementModelToJSON,
} from './DependenciesAllPackagasetsElementModel';
import type { DependenciesPackagesElementModel } from './DependenciesPackagesElementModel';
import {
    DependenciesPackagesElementModelFromJSON,
    DependenciesPackagesElementModelFromJSONTyped,
    DependenciesPackagesElementModelToJSON,
} from './DependenciesPackagesElementModel';

/**
 * 
 * @export
 * @interface DependenciesPackagesModel
 */
export interface DependenciesPackagesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof DependenciesPackagesModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof DependenciesPackagesModel
     */
    length?: number;
    /**
     * package dependencies list
     * @type {Array<DependenciesPackagesElementModel>}
     * @memberof DependenciesPackagesModel
     */
    packages?: Array<DependenciesPackagesElementModel>;
    /**
     * list of package sets with binary package count
     * @type {Array<DependenciesAllPackagasetsElementModel>}
     * @memberof DependenciesPackagesModel
     */
    branches?: Array<DependenciesAllPackagasetsElementModel>;
}

/**
 * Check if a given object implements the DependenciesPackagesModel interface.
 */
export function instanceOfDependenciesPackagesModel(value: object): value is DependenciesPackagesModel {
    return true;
}

export function DependenciesPackagesModelFromJSON(json: any): DependenciesPackagesModel {
    return DependenciesPackagesModelFromJSONTyped(json, false);
}

export function DependenciesPackagesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DependenciesPackagesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(DependenciesPackagesElementModelFromJSON)),
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(DependenciesAllPackagasetsElementModelFromJSON)),
    };
}

export function DependenciesPackagesModelToJSON(value?: DependenciesPackagesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(DependenciesPackagesElementModelToJSON)),
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(DependenciesAllPackagasetsElementModelToJSON)),
    };
}

