/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DependenciesPackageInfoElementModel
 */
export interface DependenciesPackageInfoElementModel {
    /**
     * package name
     * @type {string}
     * @memberof DependenciesPackageInfoElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof DependenciesPackageInfoElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof DependenciesPackageInfoElementModel
     */
    release?: string;
    /**
     * package summary
     * @type {string}
     * @memberof DependenciesPackageInfoElementModel
     */
    summary?: string;
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof DependenciesPackageInfoElementModel
     */
    pkghash?: string;
}

/**
 * Check if a given object implements the DependenciesPackageInfoElementModel interface.
 */
export function instanceOfDependenciesPackageInfoElementModel(value: object): value is DependenciesPackageInfoElementModel {
    return true;
}

export function DependenciesPackageInfoElementModelFromJSON(json: any): DependenciesPackageInfoElementModel {
    return DependenciesPackageInfoElementModelFromJSONTyped(json, false);
}

export function DependenciesPackageInfoElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DependenciesPackageInfoElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'pkghash': json['pkghash'] == null ? undefined : json['pkghash'],
    };
}

export function DependenciesPackageInfoElementModelToJSON(value?: DependenciesPackageInfoElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'summary': value['summary'],
        'pkghash': value['pkghash'],
    };
}

