/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrataPackageUpdateModel } from './ErrataPackageUpdateModel';
import {
    ErrataPackageUpdateModelFromJSON,
    ErrataPackageUpdateModelFromJSONTyped,
    ErrataPackageUpdateModelToJSON,
} from './ErrataPackageUpdateModel';

/**
 * 
 * @export
 * @interface ErrataPackagesUpdatesModel
 */
export interface ErrataPackagesUpdatesModel {
    /**
     * list of packages updates
     * @type {Array<ErrataPackageUpdateModel>}
     * @memberof ErrataPackagesUpdatesModel
     */
    packagesUpdates?: Array<ErrataPackageUpdateModel>;
}

/**
 * Check if a given object implements the ErrataPackagesUpdatesModel interface.
 */
export function instanceOfErrataPackagesUpdatesModel(value: object): value is ErrataPackagesUpdatesModel {
    return true;
}

export function ErrataPackagesUpdatesModelFromJSON(json: any): ErrataPackagesUpdatesModel {
    return ErrataPackagesUpdatesModelFromJSONTyped(json, false);
}

export function ErrataPackagesUpdatesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataPackagesUpdatesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'packagesUpdates': json['packages_updates'] == null ? undefined : ((json['packages_updates'] as Array<any>).map(ErrataPackageUpdateModelFromJSON)),
    };
}

export function ErrataPackagesUpdatesModelToJSON(value?: ErrataPackagesUpdatesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'packages_updates': value['packagesUpdates'] == null ? undefined : ((value['packagesUpdates'] as Array<any>).map(ErrataPackageUpdateModelToJSON)),
    };
}

