/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrataReferenceModel } from './ErrataReferenceModel';
import {
    ErrataReferenceModelFromJSON,
    ErrataReferenceModelFromJSONTyped,
    ErrataReferenceModelToJSON,
} from './ErrataReferenceModel';

/**
 * 
 * @export
 * @interface ErrataModel
 */
export interface ErrataModel {
    /**
     * errata id
     * @type {string}
     * @memberof ErrataModel
     */
    id?: string;
    /**
     * errata type
     * @type {string}
     * @memberof ErrataModel
     */
    type?: string;
    /**
     * errata created date
     * @type {Date}
     * @memberof ErrataModel
     */
    created?: Date;
    /**
     * errata updated date
     * @type {Date}
     * @memberof ErrataModel
     */
    updated?: Date;
    /**
     * packageset name
     * @type {string}
     * @memberof ErrataModel
     */
    pkgsetName?: string;
    /**
     * task id
     * @type {number}
     * @memberof ErrataModel
     */
    taskId?: number;
    /**
     * subtask id
     * @type {number}
     * @memberof ErrataModel
     */
    subtaskId?: number;
    /**
     * task state
     * @type {string}
     * @memberof ErrataModel
     */
    taskState?: string;
    /**
     * package hash
     * @type {string}
     * @memberof ErrataModel
     */
    pkgHash?: string;
    /**
     * package name
     * @type {string}
     * @memberof ErrataModel
     */
    pkgName?: string;
    /**
     * package version
     * @type {string}
     * @memberof ErrataModel
     */
    pkgVersion?: string;
    /**
     * package release
     * @type {string}
     * @memberof ErrataModel
     */
    pkgRelease?: string;
    /**
     * list of references
     * @type {Array<ErrataReferenceModel>}
     * @memberof ErrataModel
     */
    references?: Array<ErrataReferenceModel>;
}

/**
 * Check if a given object implements the ErrataModel interface.
 */
export function instanceOfErrataModel(value: object): value is ErrataModel {
    return true;
}

export function ErrataModelFromJSON(json: any): ErrataModel {
    return ErrataModelFromJSONTyped(json, false);
}

export function ErrataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'pkgsetName': json['pkgset_name'] == null ? undefined : json['pkgset_name'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'subtaskId': json['subtask_id'] == null ? undefined : json['subtask_id'],
        'taskState': json['task_state'] == null ? undefined : json['task_state'],
        'pkgHash': json['pkg_hash'] == null ? undefined : json['pkg_hash'],
        'pkgName': json['pkg_name'] == null ? undefined : json['pkg_name'],
        'pkgVersion': json['pkg_version'] == null ? undefined : json['pkg_version'],
        'pkgRelease': json['pkg_release'] == null ? undefined : json['pkg_release'],
        'references': json['references'] == null ? undefined : ((json['references'] as Array<any>).map(ErrataReferenceModelFromJSON)),
    };
}

export function ErrataModelToJSON(value?: ErrataModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString().substring(0,10)),
        'updated': value['updated'] == null ? undefined : ((value['updated']).toISOString().substring(0,10)),
        'pkgset_name': value['pkgsetName'],
        'task_id': value['taskId'],
        'subtask_id': value['subtaskId'],
        'task_state': value['taskState'],
        'pkg_hash': value['pkgHash'],
        'pkg_name': value['pkgName'],
        'pkg_version': value['pkgVersion'],
        'pkg_release': value['pkgRelease'],
        'references': value['references'] == null ? undefined : ((value['references'] as Array<any>).map(ErrataReferenceModelToJSON)),
    };
}

