/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrataJsonPostListModel
 */
export interface ErrataJsonPostListModel {
    /**
     * errata ids list
     * @type {Array<string>}
     * @memberof ErrataJsonPostListModel
     */
    errataIds: Array<string>;
}

/**
 * Check if a given object implements the ErrataJsonPostListModel interface.
 */
export function instanceOfErrataJsonPostListModel(value: object): value is ErrataJsonPostListModel {
    if (!('errataIds' in value) || value['errataIds'] === undefined) return false;
    return true;
}

export function ErrataJsonPostListModelFromJSON(json: any): ErrataJsonPostListModel {
    return ErrataJsonPostListModelFromJSONTyped(json, false);
}

export function ErrataJsonPostListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataJsonPostListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'errataIds': json['errata_ids'],
    };
}

export function ErrataJsonPostListModelToJSON(value?: ErrataJsonPostListModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errata_ids': value['errataIds'],
    };
}

