/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrataModel } from './ErrataModel';
import {
    ErrataModelFromJSON,
    ErrataModelFromJSONTyped,
    ErrataModelToJSON,
} from './ErrataModel';

/**
 * 
 * @export
 * @interface ErratasModel
 */
export interface ErratasModel {
    /**
     * list of erratas
     * @type {Array<ErrataModel>}
     * @memberof ErratasModel
     */
    erratas?: Array<ErrataModel>;
}

/**
 * Check if a given object implements the ErratasModel interface.
 */
export function instanceOfErratasModel(value: object): value is ErratasModel {
    return true;
}

export function ErratasModelFromJSON(json: any): ErratasModel {
    return ErratasModelFromJSONTyped(json, false);
}

export function ErratasModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErratasModel {
    if (json == null) {
        return json;
    }
    return {
        
        'erratas': json['erratas'] == null ? undefined : ((json['erratas'] as Array<any>).map(ErrataModelFromJSON)),
    };
}

export function ErratasModelToJSON(value?: ErratasModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'erratas': value['erratas'] == null ? undefined : ((value['erratas'] as Array<any>).map(ErrataModelToJSON)),
    };
}

