/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VulnerabilitiesElementModel } from './VulnerabilitiesElementModel';
import {
    VulnerabilitiesElementModelFromJSON,
    VulnerabilitiesElementModelFromJSONTyped,
    VulnerabilitiesElementModelToJSON,
} from './VulnerabilitiesElementModel';
import type { PackagesElementModel } from './PackagesElementModel';
import {
    PackagesElementModelFromJSON,
    PackagesElementModelFromJSONTyped,
    PackagesElementModelToJSON,
} from './PackagesElementModel';

/**
 * 
 * @export
 * @interface ErrataLastChangedElementModel
 */
export interface ErrataLastChangedElementModel {
    /**
     * is errata discarded
     * @type {boolean}
     * @memberof ErrataLastChangedElementModel
     */
    isDiscarded?: boolean;
    /**
     * errata ID
     * @type {string}
     * @memberof ErrataLastChangedElementModel
     */
    errataId?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrataLastChangedElementModel
     */
    ehType?: string;
    /**
     * task ID
     * @type {number}
     * @memberof ErrataLastChangedElementModel
     */
    taskId?: number;
    /**
     * changed
     * @type {Date}
     * @memberof ErrataLastChangedElementModel
     */
    changed?: Date;
    /**
     * package set name
     * @type {string}
     * @memberof ErrataLastChangedElementModel
     */
    branch?: string;
    /**
     * affected packages
     * @type {Array<PackagesElementModel>}
     * @memberof ErrataLastChangedElementModel
     */
    packages?: Array<PackagesElementModel>;
    /**
     * fixed vulnerabilities list
     * @type {Array<VulnerabilitiesElementModel>}
     * @memberof ErrataLastChangedElementModel
     */
    vulnerabilities?: Array<VulnerabilitiesElementModel>;
}

/**
 * Check if a given object implements the ErrataLastChangedElementModel interface.
 */
export function instanceOfErrataLastChangedElementModel(value: object): value is ErrataLastChangedElementModel {
    return true;
}

export function ErrataLastChangedElementModelFromJSON(json: any): ErrataLastChangedElementModel {
    return ErrataLastChangedElementModelFromJSONTyped(json, false);
}

export function ErrataLastChangedElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataLastChangedElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'isDiscarded': json['is_discarded'] == null ? undefined : json['is_discarded'],
        'errataId': json['errata_id'] == null ? undefined : json['errata_id'],
        'ehType': json['eh_type'] == null ? undefined : json['eh_type'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'changed': json['changed'] == null ? undefined : (new Date(json['changed'])),
        'branch': json['branch'] == null ? undefined : json['branch'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(PackagesElementModelFromJSON)),
        'vulnerabilities': json['vulnerabilities'] == null ? undefined : ((json['vulnerabilities'] as Array<any>).map(VulnerabilitiesElementModelFromJSON)),
    };
}

export function ErrataLastChangedElementModelToJSON(value?: ErrataLastChangedElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'is_discarded': value['isDiscarded'],
        'errata_id': value['errataId'],
        'eh_type': value['ehType'],
        'task_id': value['taskId'],
        'changed': value['changed'] == null ? undefined : ((value['changed']).toISOString()),
        'branch': value['branch'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(PackagesElementModelToJSON)),
        'vulnerabilities': value['vulnerabilities'] == null ? undefined : ((value['vulnerabilities'] as Array<any>).map(VulnerabilitiesElementModelToJSON)),
    };
}

