/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrataBugModel
 */
export interface ErrataBugModel {
    /**
     * bug id
     * @type {number}
     * @memberof ErrataBugModel
     */
    id?: number;
    /**
     * bug summary
     * @type {string}
     * @memberof ErrataBugModel
     */
    summary?: string;
    /**
     * bug information is valid
     * @type {boolean}
     * @memberof ErrataBugModel
     */
    isValid?: boolean;
}

/**
 * Check if a given object implements the ErrataBugModel interface.
 */
export function instanceOfErrataBugModel(value: object): value is ErrataBugModel {
    return true;
}

export function ErrataBugModelFromJSON(json: any): ErrataBugModel {
    return ErrataBugModelFromJSONTyped(json, false);
}

export function ErrataBugModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataBugModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'isValid': json['is_valid'] == null ? undefined : json['is_valid'],
    };
}

export function ErrataBugModelToJSON(value?: ErrataBugModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'summary': value['summary'],
        'is_valid': value['isValid'],
    };
}

