/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrataIdsListModel
 */
export interface ErrataIdsListModel {
    /**
     * errata ids list
     * @type {Array<string>}
     * @memberof ErrataIdsListModel
     */
    errataIds?: Array<string>;
}

/**
 * Check if a given object implements the ErrataIdsListModel interface.
 */
export function instanceOfErrataIdsListModel(value: object): value is ErrataIdsListModel {
    return true;
}

export function ErrataIdsListModelFromJSON(json: any): ErrataIdsListModel {
    return ErrataIdsListModelFromJSONTyped(json, false);
}

export function ErrataIdsListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataIdsListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'errataIds': json['errata_ids'] == null ? undefined : json['errata_ids'],
    };
}

export function ErrataIdsListModelToJSON(value?: ErrataIdsListModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errata_ids': value['errataIds'],
    };
}

