/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrataBranchesModel
 */
export interface ErrataBranchesModel {
    /**
     * number of branches
     * @type {number}
     * @memberof ErrataBranchesModel
     */
    length?: number;
    /**
     * list of branches
     * @type {Array<string>}
     * @memberof ErrataBranchesModel
     */
    branches?: Array<string>;
}

/**
 * Check if a given object implements the ErrataBranchesModel interface.
 */
export function instanceOfErrataBranchesModel(value: object): value is ErrataBranchesModel {
    return true;
}

export function ErrataBranchesModelFromJSON(json: any): ErrataBranchesModel {
    return ErrataBranchesModelFromJSONTyped(json, false);
}

export function ErrataBranchesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataBranchesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'branches': json['branches'] == null ? undefined : json['branches'],
    };
}

export function ErrataBranchesModelToJSON(value?: ErrataBranchesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
        'branches': value['branches'],
    };
}

