/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrataReferenceModel
 */
export interface ErrataReferenceModel {
    /**
     * errata id
     * @type {string}
     * @memberof ErrataReferenceModel
     */
    id?: string;
    /**
     * errata type
     * @type {string}
     * @memberof ErrataReferenceModel
     */
    type?: string;
}

/**
 * Check if a given object implements the ErrataReferenceModel interface.
 */
export function instanceOfErrataReferenceModel(value: object): value is ErrataReferenceModel {
    return true;
}

export function ErrataReferenceModelFromJSON(json: any): ErrataReferenceModel {
    return ErrataReferenceModelFromJSONTyped(json, false);
}

export function ErrataReferenceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrataReferenceModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ErrataReferenceModelToJSON(value?: ErrataReferenceModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

