/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FastDependencySearchElementModel
 */
export interface FastDependencySearchElementModel {
    /**
     * the name of the dependent package
     * @type {string}
     * @memberof FastDependencySearchElementModel
     */
    dpName?: string;
}

/**
 * Check if a given object implements the FastDependencySearchElementModel interface.
 */
export function instanceOfFastDependencySearchElementModel(value: object): value is FastDependencySearchElementModel {
    return true;
}

export function FastDependencySearchElementModelFromJSON(json: any): FastDependencySearchElementModel {
    return FastDependencySearchElementModelFromJSONTyped(json, false);
}

export function FastDependencySearchElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FastDependencySearchElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'dpName': json['dp_name'] == null ? undefined : json['dp_name'],
    };
}

export function FastDependencySearchElementModelToJSON(value?: FastDependencySearchElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dp_name': value['dpName'],
    };
}

