/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FastDependencySearchElementModel } from './FastDependencySearchElementModel';
import {
    FastDependencySearchElementModelFromJSON,
    FastDependencySearchElementModelFromJSONTyped,
    FastDependencySearchElementModelToJSON,
} from './FastDependencySearchElementModel';

/**
 * 
 * @export
 * @interface FastDependencySearchModel
 */
export interface FastDependencySearchModel {
    /**
     * request arguments
     * @type {object}
     * @memberof FastDependencySearchModel
     */
    requestArgs?: object;
    /**
     * number of dependencies found
     * @type {number}
     * @memberof FastDependencySearchModel
     */
    length?: number;
    /**
     * dependency list
     * @type {Array<FastDependencySearchElementModel>}
     * @memberof FastDependencySearchModel
     */
    dependencies?: Array<FastDependencySearchElementModel>;
}

/**
 * Check if a given object implements the FastDependencySearchModel interface.
 */
export function instanceOfFastDependencySearchModel(value: object): value is FastDependencySearchModel {
    return true;
}

export function FastDependencySearchModelFromJSON(json: any): FastDependencySearchModel {
    return FastDependencySearchModelFromJSONTyped(json, false);
}

export function FastDependencySearchModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FastDependencySearchModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'dependencies': json['dependencies'] == null ? undefined : ((json['dependencies'] as Array<any>).map(FastDependencySearchElementModelFromJSON)),
    };
}

export function FastDependencySearchModelToJSON(value?: FastDependencySearchModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'dependencies': value['dependencies'] == null ? undefined : ((value['dependencies'] as Array<any>).map(FastDependencySearchElementModelToJSON)),
    };
}

