/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilesElementModel
 */
export interface FilesElementModel {
    /**
     * file name
     * @type {string}
     * @memberof FilesElementModel
     */
    fileName?: string;
    /**
     * hash from the filename
     * @type {string}
     * @memberof FilesElementModel
     */
    fileHashname?: string;
    /**
     * file class
     * @type {string}
     * @memberof FilesElementModel
     */
    fileClass?: string;
    /**
     * link path
     * @type {string}
     * @memberof FilesElementModel
     */
    symlink?: string;
    /**
     * file permissions string representation
     * @type {string}
     * @memberof FilesElementModel
     */
    fileMode?: string;
}

/**
 * Check if a given object implements the FilesElementModel interface.
 */
export function instanceOfFilesElementModel(value: object): value is FilesElementModel {
    return true;
}

export function FilesElementModelFromJSON(json: any): FilesElementModel {
    return FilesElementModelFromJSONTyped(json, false);
}

export function FilesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'fileHashname': json['file_hashname'] == null ? undefined : json['file_hashname'],
        'fileClass': json['file_class'] == null ? undefined : json['file_class'],
        'symlink': json['symlink'] == null ? undefined : json['symlink'],
        'fileMode': json['file_mode'] == null ? undefined : json['file_mode'],
    };
}

export function FilesElementModelToJSON(value?: FilesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_name': value['fileName'],
        'file_hashname': value['fileHashname'],
        'file_class': value['fileClass'],
        'symlink': value['symlink'],
        'file_mode': value['fileMode'],
    };
}

