/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindImagesByPackageElementModel } from './FindImagesByPackageElementModel';
import {
    FindImagesByPackageElementModelFromJSON,
    FindImagesByPackageElementModelFromJSONTyped,
    FindImagesByPackageElementModelToJSON,
} from './FindImagesByPackageElementModel';

/**
 * 
 * @export
 * @interface FindImagesByPackageModel
 */
export interface FindImagesByPackageModel {
    /**
     * request arguments
     * @type {object}
     * @memberof FindImagesByPackageModel
     */
    requestArgs?: object;
    /**
     * number of images found
     * @type {number}
     * @memberof FindImagesByPackageModel
     */
    length?: number;
    /**
     * list of found images
     * @type {Array<FindImagesByPackageElementModel>}
     * @memberof FindImagesByPackageModel
     */
    images?: Array<FindImagesByPackageElementModel>;
}

/**
 * Check if a given object implements the FindImagesByPackageModel interface.
 */
export function instanceOfFindImagesByPackageModel(value: object): value is FindImagesByPackageModel {
    return true;
}

export function FindImagesByPackageModelFromJSON(json: any): FindImagesByPackageModel {
    return FindImagesByPackageModelFromJSONTyped(json, false);
}

export function FindImagesByPackageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindImagesByPackageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(FindImagesByPackageElementModelFromJSON)),
    };
}

export function FindImagesByPackageModelToJSON(value?: FindImagesByPackageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(FindImagesByPackageElementModelToJSON)),
    };
}

