/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindTasksElementModel } from './FindTasksElementModel';
import {
    FindTasksElementModelFromJSON,
    FindTasksElementModelFromJSONTyped,
    FindTasksElementModelToJSON,
} from './FindTasksElementModel';

/**
 * 
 * @export
 * @interface FindTasksModel
 */
export interface FindTasksModel {
    /**
     * request arguments
     * @type {object}
     * @memberof FindTasksModel
     */
    requestArgs?: object;
    /**
     * number of tasks found
     * @type {number}
     * @memberof FindTasksModel
     */
    length?: number;
    /**
     * list of found tasks
     * @type {Array<FindTasksElementModel>}
     * @memberof FindTasksModel
     */
    tasks?: Array<FindTasksElementModel>;
}

/**
 * Check if a given object implements the FindTasksModel interface.
 */
export function instanceOfFindTasksModel(value: object): value is FindTasksModel {
    return true;
}

export function FindTasksModelFromJSON(json: any): FindTasksModel {
    return FindTasksModelFromJSONTyped(json, false);
}

export function FindTasksModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindTasksModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(FindTasksElementModelFromJSON)),
    };
}

export function FindTasksModelToJSON(value?: FindTasksModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(FindTasksElementModelToJSON)),
    };
}

