/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindImagesByTaskIterationElementModel
 */
export interface FindImagesByTaskIterationElementModel {
    /**
     * task try
     * @type {number}
     * @memberof FindImagesByTaskIterationElementModel
     */
    taskTry?: number;
    /**
     * task iter
     * @type {number}
     * @memberof FindImagesByTaskIterationElementModel
     */
    taskIter?: number;
}

/**
 * Check if a given object implements the FindImagesByTaskIterationElementModel interface.
 */
export function instanceOfFindImagesByTaskIterationElementModel(value: object): value is FindImagesByTaskIterationElementModel {
    return true;
}

export function FindImagesByTaskIterationElementModelFromJSON(json: any): FindImagesByTaskIterationElementModel {
    return FindImagesByTaskIterationElementModelFromJSONTyped(json, false);
}

export function FindImagesByTaskIterationElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindImagesByTaskIterationElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'taskTry': json['task_try'] == null ? undefined : json['task_try'],
        'taskIter': json['task_iter'] == null ? undefined : json['task_iter'],
    };
}

export function FindImagesByTaskIterationElementModelToJSON(value?: FindImagesByTaskIterationElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task_try': value['taskTry'],
        'task_iter': value['taskIter'],
    };
}

