/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageAllISOElementModel
 */
export interface ImageAllISOElementModel {
    /**
     * ISO image base branch
     * @type {string}
     * @memberof ImageAllISOElementModel
     */
    branch?: string;
    /**
     * ISO image package set name
     * @type {string}
     * @memberof ImageAllISOElementModel
     */
    name?: string;
    /**
     * ISO image package set tag
     * @type {string}
     * @memberof ImageAllISOElementModel
     */
    tag?: string;
    /**
     * ISO image file name
     * @type {string}
     * @memberof ImageAllISOElementModel
     */
    file?: string;
    /**
     * ISO image package set date
     * @type {Date}
     * @memberof ImageAllISOElementModel
     */
    date?: Date;
    /**
     * ISO image package set UUID
     * @type {string}
     * @memberof ImageAllISOElementModel
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ImageAllISOElementModel interface.
 */
export function instanceOfImageAllISOElementModel(value: object): value is ImageAllISOElementModel {
    return true;
}

export function ImageAllISOElementModelFromJSON(json: any): ImageAllISOElementModel {
    return ImageAllISOElementModelFromJSONTyped(json, false);
}

export function ImageAllISOElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageAllISOElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'name': json['name'] == null ? undefined : json['name'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'file': json['file'] == null ? undefined : json['file'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ImageAllISOElementModelToJSON(value?: ImageAllISOElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'branch': value['branch'],
        'name': value['name'],
        'tag': value['tag'],
        'file': value['file'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'uuid': value['uuid'],
    };
}

