/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageErrataElementModel } from './ImageErrataElementModel';
import {
    ImageErrataElementModelFromJSON,
    ImageErrataElementModelFromJSONTyped,
    ImageErrataElementModelToJSON,
} from './ImageErrataElementModel';

/**
 * 
 * @export
 * @interface ImageErrataModel
 */
export interface ImageErrataModel {
    /**
     * request arguments
     * @type {object}
     * @memberof ImageErrataModel
     */
    requestArgs?: object;
    /**
     * number of erratas
     * @type {number}
     * @memberof ImageErrataModel
     */
    length?: number;
    /**
     * image errata list
     * @type {Array<ImageErrataElementModel>}
     * @memberof ImageErrataModel
     */
    erratas?: Array<ImageErrataElementModel>;
}

/**
 * Check if a given object implements the ImageErrataModel interface.
 */
export function instanceOfImageErrataModel(value: object): value is ImageErrataModel {
    return true;
}

export function ImageErrataModelFromJSON(json: any): ImageErrataModel {
    return ImageErrataModelFromJSONTyped(json, false);
}

export function ImageErrataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageErrataModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'erratas': json['erratas'] == null ? undefined : ((json['erratas'] as Array<any>).map(ImageErrataElementModelFromJSON)),
    };
}

export function ImageErrataModelToJSON(value?: ImageErrataModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'erratas': value['erratas'] == null ? undefined : ((value['erratas'] as Array<any>).map(ImageErrataElementModelToJSON)),
    };
}

