/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageInfoComponentModel } from './ImageInfoComponentModel';
import {
    ImageInfoComponentModelFromJSON,
    ImageInfoComponentModelFromJSONTyped,
    ImageInfoComponentModelToJSON,
} from './ImageInfoComponentModel';

/**
 * 
 * @export
 * @interface ImageInfoElementModel
 */
export interface ImageInfoElementModel {
    /**
     * Image package set date
     * @type {Date}
     * @memberof ImageInfoElementModel
     */
    date?: Date;
    /**
     * Image package set UUID
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    uuid?: string;
    /**
     * Image package set tag
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    tag?: string;
    /**
     * Image base branch
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    branch?: string;
    /**
     * Image edition
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    edition?: string;
    /**
     * Image flavor
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    flavor?: string;
    /**
     * Image platform
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    platform?: string;
    /**
     * Image release type
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    release?: string;
    /**
     * Image version major
     * @type {number}
     * @memberof ImageInfoElementModel
     */
    versionMajor?: number;
    /**
     * Image version minor
     * @type {number}
     * @memberof ImageInfoElementModel
     */
    versionMinor?: number;
    /**
     * Image version sub
     * @type {number}
     * @memberof ImageInfoElementModel
     */
    versionSub?: number;
    /**
     * Image architecture
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    arch?: string;
    /**
     * Image variant
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    variant?: string;
    /**
     * Image type
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    type?: string;
    /**
     * Image file name
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    file?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageInfoElementModel
     */
    url?: Array<string>;
    /**
     * Image MD5 checksum
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    md5sum?: string;
    /**
     * Image GOST12 checksum
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    gost12sum?: string;
    /**
     * Image SHA256 checksum
     * @type {string}
     * @memberof ImageInfoElementModel
     */
    sha256sum?: string;
    /**
     * list of image components information
     * @type {Array<ImageInfoComponentModel>}
     * @memberof ImageInfoElementModel
     */
    components?: Array<ImageInfoComponentModel>;
}

/**
 * Check if a given object implements the ImageInfoElementModel interface.
 */
export function instanceOfImageInfoElementModel(value: object): value is ImageInfoElementModel {
    return true;
}

export function ImageInfoElementModelFromJSON(json: any): ImageInfoElementModel {
    return ImageInfoElementModelFromJSONTyped(json, false);
}

export function ImageInfoElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageInfoElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'edition': json['edition'] == null ? undefined : json['edition'],
        'flavor': json['flavor'] == null ? undefined : json['flavor'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'release': json['release'] == null ? undefined : json['release'],
        'versionMajor': json['version_major'] == null ? undefined : json['version_major'],
        'versionMinor': json['version_minor'] == null ? undefined : json['version_minor'],
        'versionSub': json['version_sub'] == null ? undefined : json['version_sub'],
        'arch': json['arch'] == null ? undefined : json['arch'],
        'variant': json['variant'] == null ? undefined : json['variant'],
        'type': json['type'] == null ? undefined : json['type'],
        'file': json['file'] == null ? undefined : json['file'],
        'url': json['url'] == null ? undefined : json['url'],
        'md5sum': json['md5sum'] == null ? undefined : json['md5sum'],
        'gost12sum': json['gost12sum'] == null ? undefined : json['gost12sum'],
        'sha256sum': json['sha256sum'] == null ? undefined : json['sha256sum'],
        'components': json['components'] == null ? undefined : ((json['components'] as Array<any>).map(ImageInfoComponentModelFromJSON)),
    };
}

export function ImageInfoElementModelToJSON(value?: ImageInfoElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'uuid': value['uuid'],
        'tag': value['tag'],
        'branch': value['branch'],
        'edition': value['edition'],
        'flavor': value['flavor'],
        'platform': value['platform'],
        'release': value['release'],
        'version_major': value['versionMajor'],
        'version_minor': value['versionMinor'],
        'version_sub': value['versionSub'],
        'arch': value['arch'],
        'variant': value['variant'],
        'type': value['type'],
        'file': value['file'],
        'url': value['url'],
        'md5sum': value['md5sum'],
        'gost12sum': value['gost12sum'],
        'sha256sum': value['sha256sum'],
        'components': value['components'] == null ? undefined : ((value['components'] as Array<any>).map(ImageInfoComponentModelToJSON)),
    };
}

