/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageAllISOElementModel } from './ImageAllISOElementModel';
import {
    ImageAllISOElementModelFromJSON,
    ImageAllISOElementModelFromJSONTyped,
    ImageAllISOElementModelToJSON,
} from './ImageAllISOElementModel';

/**
 * 
 * @export
 * @interface ImageAllISOModel
 */
export interface ImageAllISOModel {
    /**
     * number of ISO images
     * @type {number}
     * @memberof ImageAllISOModel
     */
    length?: number;
    /**
     * list of ISO images package sets information
     * @type {Array<ImageAllISOElementModel>}
     * @memberof ImageAllISOModel
     */
    images?: Array<ImageAllISOElementModel>;
}

/**
 * Check if a given object implements the ImageAllISOModel interface.
 */
export function instanceOfImageAllISOModel(value: object): value is ImageAllISOModel {
    return true;
}

export function ImageAllISOModelFromJSON(json: any): ImageAllISOModel {
    return ImageAllISOModelFromJSONTyped(json, false);
}

export function ImageAllISOModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageAllISOModel {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageAllISOElementModelFromJSON)),
    };
}

export function ImageAllISOModelToJSON(value?: ImageAllISOModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageAllISOElementModelToJSON)),
    };
}

