/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageStatusGetElementModel
 */
export interface ImageStatusGetElementModel {
    /**
     * ISO image base branch
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    branch?: string;
    /**
     * ISO image edition
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    edition?: string;
    /**
     * ISO image name
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    name?: string;
    /**
     * hide - hide image, show - show image
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    show?: string;
    /**
     * support start date
     * @type {Date}
     * @memberof ImageStatusGetElementModel
     */
    startDate?: Date;
    /**
     * support end date
     * @type {Date}
     * @memberof ImageStatusGetElementModel
     */
    endDate?: Date;
    /**
     * image summary in Russian
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    summaryRu?: string;
    /**
     * image summary in English
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    summaryEn?: string;
    /**
     * html description in Russian in Base64 format
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    descriptionRu?: string;
    /**
     * html description in English in Base64 format
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    descriptionEn?: string;
    /**
     * link to mailing list
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    mailingList?: string;
    /**
     * image name for bugzilla
     * @type {string}
     * @memberof ImageStatusGetElementModel
     */
    nameBugzilla?: string;
    /**
     * image mirror's auxilary info as JSON substructure
     * @type {object}
     * @memberof ImageStatusGetElementModel
     */
    json?: object;
}

/**
 * Check if a given object implements the ImageStatusGetElementModel interface.
 */
export function instanceOfImageStatusGetElementModel(value: object): value is ImageStatusGetElementModel {
    return true;
}

export function ImageStatusGetElementModelFromJSON(json: any): ImageStatusGetElementModel {
    return ImageStatusGetElementModelFromJSONTyped(json, false);
}

export function ImageStatusGetElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageStatusGetElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'edition': json['edition'] == null ? undefined : json['edition'],
        'name': json['name'] == null ? undefined : json['name'],
        'show': json['show'] == null ? undefined : json['show'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'summaryRu': json['summary_ru'] == null ? undefined : json['summary_ru'],
        'summaryEn': json['summary_en'] == null ? undefined : json['summary_en'],
        'descriptionRu': json['description_ru'] == null ? undefined : json['description_ru'],
        'descriptionEn': json['description_en'] == null ? undefined : json['description_en'],
        'mailingList': json['mailing_list'] == null ? undefined : json['mailing_list'],
        'nameBugzilla': json['name_bugzilla'] == null ? undefined : json['name_bugzilla'],
        'json': json['json'] == null ? undefined : json['json'],
    };
}

export function ImageStatusGetElementModelToJSON(value?: ImageStatusGetElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'branch': value['branch'],
        'edition': value['edition'],
        'name': value['name'],
        'show': value['show'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'summary_ru': value['summaryRu'],
        'summary_en': value['summaryEn'],
        'description_ru': value['descriptionRu'],
        'description_en': value['descriptionEn'],
        'mailing_list': value['mailingList'],
        'name_bugzilla': value['nameBugzilla'],
        'json': value['json'],
    };
}

