/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImagePackagesElement2Model
 */
export interface ImagePackagesElement2Model {
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof ImagePackagesElement2Model
     */
    hash?: string;
    /**
     * package architecture
     * @type {string}
     * @memberof ImagePackagesElement2Model
     */
    arch?: string;
    /**
     * package name
     * @type {string}
     * @memberof ImagePackagesElement2Model
     */
    name?: string;
    /**
     * package epoch
     * @type {number}
     * @memberof ImagePackagesElement2Model
     */
    epoch?: number;
    /**
     * package version
     * @type {string}
     * @memberof ImagePackagesElement2Model
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof ImagePackagesElement2Model
     */
    release?: string;
    /**
     * package disttag
     * @type {string}
     * @memberof ImagePackagesElement2Model
     */
    disttag?: string;
    /**
     * package build time
     * @type {number}
     * @memberof ImagePackagesElement2Model
     */
    buildtime?: number;
    /**
     * build task id
     * @type {number}
     * @memberof ImagePackagesElement2Model
     */
    taskId?: number;
    /**
     * build task subtask id
     * @type {number}
     * @memberof ImagePackagesElement2Model
     */
    subtaskId?: number;
}

/**
 * Check if a given object implements the ImagePackagesElement2Model interface.
 */
export function instanceOfImagePackagesElement2Model(value: object): value is ImagePackagesElement2Model {
    return true;
}

export function ImagePackagesElement2ModelFromJSON(json: any): ImagePackagesElement2Model {
    return ImagePackagesElement2ModelFromJSONTyped(json, false);
}

export function ImagePackagesElement2ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagePackagesElement2Model {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'] == null ? undefined : json['hash'],
        'arch': json['arch'] == null ? undefined : json['arch'],
        'name': json['name'] == null ? undefined : json['name'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'disttag': json['disttag'] == null ? undefined : json['disttag'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'subtaskId': json['subtask_id'] == null ? undefined : json['subtask_id'],
    };
}

export function ImagePackagesElement2ModelToJSON(value?: ImagePackagesElement2Model | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': value['hash'],
        'arch': value['arch'],
        'name': value['name'],
        'epoch': value['epoch'],
        'version': value['version'],
        'release': value['release'],
        'disttag': value['disttag'],
        'buildtime': value['buildtime'],
        'task_id': value['taskId'],
        'subtask_id': value['subtaskId'],
    };
}

