/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VulnerabilitiesElementModel } from './VulnerabilitiesElementModel';
import {
    VulnerabilitiesElementModelFromJSON,
    VulnerabilitiesElementModelFromJSONTyped,
    VulnerabilitiesElementModelToJSON,
} from './VulnerabilitiesElementModel';

/**
 * 
 * @export
 * @interface ImageErrataElementModel
 */
export interface ImageErrataElementModel {
    /**
     * package hash UInt64 as string in the image
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    imgHash?: string;
    /**
     * package version in the image
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    imgVersion?: string;
    /**
     * package release in the image
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    imgRelease?: string;
    /**
     * binary package name
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    pkgName?: string;
    /**
     * package architecture in the repository
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    pkgArch?: string;
    /**
     * package hash UInt64 as string in the repository
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    pkgHash?: string;
    /**
     * package version in the repository
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    pkgVersion?: string;
    /**
     * package release in the repository
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    pkgRelease?: string;
    /**
     * package summary
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    summary?: string;
    /**
     * errata ID
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    errataId?: string;
    /**
     * errata type
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    ehType?: string;
    /**
     * task ID
     * @type {number}
     * @memberof ImageErrataElementModel
     */
    taskId?: number;
    /**
     * changed
     * @type {Date}
     * @memberof ImageErrataElementModel
     */
    changed?: Date;
    /**
     * package set name
     * @type {string}
     * @memberof ImageErrataElementModel
     */
    branch?: string;
    /**
     * is errata discarded
     * @type {boolean}
     * @memberof ImageErrataElementModel
     */
    isDiscarded?: boolean;
    /**
     * fixed vulnerabilities list
     * @type {Array<VulnerabilitiesElementModel>}
     * @memberof ImageErrataElementModel
     */
    vulnerabilities?: Array<VulnerabilitiesElementModel>;
}

/**
 * Check if a given object implements the ImageErrataElementModel interface.
 */
export function instanceOfImageErrataElementModel(value: object): value is ImageErrataElementModel {
    return true;
}

export function ImageErrataElementModelFromJSON(json: any): ImageErrataElementModel {
    return ImageErrataElementModelFromJSONTyped(json, false);
}

export function ImageErrataElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageErrataElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'imgHash': json['img_hash'] == null ? undefined : json['img_hash'],
        'imgVersion': json['img_version'] == null ? undefined : json['img_version'],
        'imgRelease': json['img_release'] == null ? undefined : json['img_release'],
        'pkgName': json['pkg_name'] == null ? undefined : json['pkg_name'],
        'pkgArch': json['pkg_arch'] == null ? undefined : json['pkg_arch'],
        'pkgHash': json['pkg_hash'] == null ? undefined : json['pkg_hash'],
        'pkgVersion': json['pkg_version'] == null ? undefined : json['pkg_version'],
        'pkgRelease': json['pkg_release'] == null ? undefined : json['pkg_release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'errataId': json['errata_id'] == null ? undefined : json['errata_id'],
        'ehType': json['eh_type'] == null ? undefined : json['eh_type'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'changed': json['changed'] == null ? undefined : (new Date(json['changed'])),
        'branch': json['branch'] == null ? undefined : json['branch'],
        'isDiscarded': json['is_discarded'] == null ? undefined : json['is_discarded'],
        'vulnerabilities': json['vulnerabilities'] == null ? undefined : ((json['vulnerabilities'] as Array<any>).map(VulnerabilitiesElementModelFromJSON)),
    };
}

export function ImageErrataElementModelToJSON(value?: ImageErrataElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'img_hash': value['imgHash'],
        'img_version': value['imgVersion'],
        'img_release': value['imgRelease'],
        'pkg_name': value['pkgName'],
        'pkg_arch': value['pkgArch'],
        'pkg_hash': value['pkgHash'],
        'pkg_version': value['pkgVersion'],
        'pkg_release': value['pkgRelease'],
        'summary': value['summary'],
        'errata_id': value['errataId'],
        'eh_type': value['ehType'],
        'task_id': value['taskId'],
        'changed': value['changed'] == null ? undefined : ((value['changed']).toISOString()),
        'branch': value['branch'],
        'is_discarded': value['isDiscarded'],
        'vulnerabilities': value['vulnerabilities'] == null ? undefined : ((value['vulnerabilities'] as Array<any>).map(VulnerabilitiesElementModelToJSON)),
    };
}

