/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageTagStatusGetElementModel } from './ImageTagStatusGetElementModel';
import {
    ImageTagStatusGetElementModelFromJSON,
    ImageTagStatusGetElementModelFromJSONTyped,
    ImageTagStatusGetElementModelToJSON,
} from './ImageTagStatusGetElementModel';

/**
 * 
 * @export
 * @interface ImageTagStatusGetModel
 */
export interface ImageTagStatusGetModel {
    /**
     * image info
     * @type {Array<ImageTagStatusGetElementModel>}
     * @memberof ImageTagStatusGetModel
     */
    tags?: Array<ImageTagStatusGetElementModel>;
}

/**
 * Check if a given object implements the ImageTagStatusGetModel interface.
 */
export function instanceOfImageTagStatusGetModel(value: object): value is ImageTagStatusGetModel {
    return true;
}

export function ImageTagStatusGetModelFromJSON(json: any): ImageTagStatusGetModel {
    return ImageTagStatusGetModelFromJSONTyped(json, false);
}

export function ImageTagStatusGetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageTagStatusGetModel {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(ImageTagStatusGetElementModelFromJSON)),
    };
}

export function ImageTagStatusGetModelToJSON(value?: ImageTagStatusGetModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(ImageTagStatusGetElementModelToJSON)),
    };
}

