/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageTagJSONElementModel
 */
export interface ImageTagJSONElementModel {
    /**
     * ISO image package set tag
     * @type {string}
     * @memberof ImageTagJSONElementModel
     */
    imgTag: string;
    /**
     * hide - hide image, show - show image
     * @type {string}
     * @memberof ImageTagJSONElementModel
     */
    imgShow: string;
}

/**
 * Check if a given object implements the ImageTagJSONElementModel interface.
 */
export function instanceOfImageTagJSONElementModel(value: object): value is ImageTagJSONElementModel {
    if (!('imgTag' in value) || value['imgTag'] === undefined) return false;
    if (!('imgShow' in value) || value['imgShow'] === undefined) return false;
    return true;
}

export function ImageTagJSONElementModelFromJSON(json: any): ImageTagJSONElementModel {
    return ImageTagJSONElementModelFromJSONTyped(json, false);
}

export function ImageTagJSONElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageTagJSONElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'imgTag': json['img_tag'],
        'imgShow': json['img_show'],
    };
}

export function ImageTagJSONElementModelToJSON(value?: ImageTagJSONElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'img_tag': value['imgTag'],
        'img_show': value['imgShow'],
    };
}

