/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LastImagePackagesElementModel
 */
export interface LastImagePackagesElementModel {
    /**
     * task id
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    taskId?: string;
    /**
     * task changed date
     * @type {Date}
     * @memberof LastImagePackagesElementModel
     */
    taskChanged?: Date;
    /**
     * task type [add|delete]
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    tplanAction?: string;
    /**
     * package set name
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    branch?: string;
    /**
     * package hash UInt64 as string in the repository
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    hash?: string;
    /**
     * package name
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    name?: string;
    /**
     * package version in the repository
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    version?: string;
    /**
     * package release in the repository
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    release?: string;
    /**
     * package architecture in the repository
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    arch?: string;
    /**
     * package hash UInt64 as string in the image
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    imgHash?: string;
    /**
     * package version in the image
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    imgVersion?: string;
    /**
     * package release in the image
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    imgRelease?: string;
    /**
     * package summary
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    summary?: string;
    /**
     * package last changelog name
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    chlogName?: string;
    /**
     * maintainer nickname in the changelog
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    chlogNick?: string;
    /**
     * package last changelog message date
     * @type {Date}
     * @memberof LastImagePackagesElementModel
     */
    chlogDate?: Date;
    /**
     * package last changelog message
     * @type {string}
     * @memberof LastImagePackagesElementModel
     */
    chlogText?: string;
}

/**
 * Check if a given object implements the LastImagePackagesElementModel interface.
 */
export function instanceOfLastImagePackagesElementModel(value: object): value is LastImagePackagesElementModel {
    return true;
}

export function LastImagePackagesElementModelFromJSON(json: any): LastImagePackagesElementModel {
    return LastImagePackagesElementModelFromJSONTyped(json, false);
}

export function LastImagePackagesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LastImagePackagesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'taskChanged': json['task_changed'] == null ? undefined : (new Date(json['task_changed'])),
        'tplanAction': json['tplan_action'] == null ? undefined : json['tplan_action'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'arch': json['arch'] == null ? undefined : json['arch'],
        'imgHash': json['img_hash'] == null ? undefined : json['img_hash'],
        'imgVersion': json['img_version'] == null ? undefined : json['img_version'],
        'imgRelease': json['img_release'] == null ? undefined : json['img_release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'chlogName': json['chlog_name'] == null ? undefined : json['chlog_name'],
        'chlogNick': json['chlog_nick'] == null ? undefined : json['chlog_nick'],
        'chlogDate': json['chlog_date'] == null ? undefined : (new Date(json['chlog_date'])),
        'chlogText': json['chlog_text'] == null ? undefined : json['chlog_text'],
    };
}

export function LastImagePackagesElementModelToJSON(value?: LastImagePackagesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task_id': value['taskId'],
        'task_changed': value['taskChanged'] == null ? undefined : ((value['taskChanged']).toISOString()),
        'tplan_action': value['tplanAction'],
        'branch': value['branch'],
        'hash': value['hash'],
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'arch': value['arch'],
        'img_hash': value['imgHash'],
        'img_version': value['imgVersion'],
        'img_release': value['imgRelease'],
        'summary': value['summary'],
        'chlog_name': value['chlogName'],
        'chlog_nick': value['chlogNick'],
        'chlog_date': value['chlogDate'] == null ? undefined : ((value['chlogDate']).toISOString()),
        'chlog_text': value['chlogText'],
    };
}

