/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaintainerPackagesElementModel
 */
export interface MaintainerPackagesElementModel {
    /**
     * package name
     * @type {string}
     * @memberof MaintainerPackagesElementModel
     */
    name?: string;
    /**
     * package build time
     * @type {number}
     * @memberof MaintainerPackagesElementModel
     */
    buildtime?: number;
    /**
     * package url
     * @type {string}
     * @memberof MaintainerPackagesElementModel
     */
    url?: string;
    /**
     * package summary
     * @type {string}
     * @memberof MaintainerPackagesElementModel
     */
    summary?: string;
    /**
     * package version
     * @type {string}
     * @memberof MaintainerPackagesElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof MaintainerPackagesElementModel
     */
    release?: string;
}

/**
 * Check if a given object implements the MaintainerPackagesElementModel interface.
 */
export function instanceOfMaintainerPackagesElementModel(value: object): value is MaintainerPackagesElementModel {
    return true;
}

export function MaintainerPackagesElementModelFromJSON(json: any): MaintainerPackagesElementModel {
    return MaintainerPackagesElementModelFromJSONTyped(json, false);
}

export function MaintainerPackagesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintainerPackagesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
        'url': json['url'] == null ? undefined : json['url'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
    };
}

export function MaintainerPackagesElementModelToJSON(value?: MaintainerPackagesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'buildtime': value['buildtime'],
        'url': value['url'],
        'summary': value['summary'],
        'version': value['version'],
        'release': value['release'],
    };
}

