/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteAllPackagasetsElementModel } from './SiteAllPackagasetsElementModel';
import {
    SiteAllPackagasetsElementModelFromJSON,
    SiteAllPackagasetsElementModelFromJSONTyped,
    SiteAllPackagasetsElementModelToJSON,
} from './SiteAllPackagasetsElementModel';

/**
 * 
 * @export
 * @interface MaintainerBranchesModel
 */
export interface MaintainerBranchesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof MaintainerBranchesModel
     */
    requestArgs?: object;
    /**
     * number of maintainers found
     * @type {number}
     * @memberof MaintainerBranchesModel
     */
    length?: number;
    /**
     * all branches of the maintainer
     * @type {Array<SiteAllPackagasetsElementModel>}
     * @memberof MaintainerBranchesModel
     */
    branches?: Array<SiteAllPackagasetsElementModel>;
}

/**
 * Check if a given object implements the MaintainerBranchesModel interface.
 */
export function instanceOfMaintainerBranchesModel(value: object): value is MaintainerBranchesModel {
    return true;
}

export function MaintainerBranchesModelFromJSON(json: any): MaintainerBranchesModel {
    return MaintainerBranchesModelFromJSONTyped(json, false);
}

export function MaintainerBranchesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintainerBranchesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(SiteAllPackagasetsElementModelFromJSON)),
    };
}

export function MaintainerBranchesModelToJSON(value?: MaintainerBranchesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(SiteAllPackagasetsElementModelToJSON)),
    };
}

