/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NeedsApprovalTaskElementModel } from './NeedsApprovalTaskElementModel';
import {
    NeedsApprovalTaskElementModelFromJSON,
    NeedsApprovalTaskElementModelFromJSONTyped,
    NeedsApprovalTaskElementModelToJSON,
} from './NeedsApprovalTaskElementModel';

/**
 * 
 * @export
 * @interface NeedsApprovalModel
 */
export interface NeedsApprovalModel {
    /**
     * number of tasks found
     * @type {number}
     * @memberof NeedsApprovalModel
     */
    length?: number;
    /**
     * list of tasks
     * @type {Array<NeedsApprovalTaskElementModel>}
     * @memberof NeedsApprovalModel
     */
    tasks?: Array<NeedsApprovalTaskElementModel>;
}

/**
 * Check if a given object implements the NeedsApprovalModel interface.
 */
export function instanceOfNeedsApprovalModel(value: object): value is NeedsApprovalModel {
    return true;
}

export function NeedsApprovalModelFromJSON(json: any): NeedsApprovalModel {
    return NeedsApprovalModelFromJSONTyped(json, false);
}

export function NeedsApprovalModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NeedsApprovalModel {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(NeedsApprovalTaskElementModelFromJSON)),
    };
}

export function NeedsApprovalModelToJSON(value?: NeedsApprovalModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(NeedsApprovalTaskElementModelToJSON)),
    };
}

