/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskInfoPackageModel } from './TaskInfoPackageModel';
import {
    TaskInfoPackageModelFromJSON,
    TaskInfoPackageModelFromJSONTyped,
    TaskInfoPackageModelToJSON,
} from './TaskInfoPackageModel';

/**
 * 
 * @export
 * @interface NeedsApprovalSubtaskElementModel
 */
export interface NeedsApprovalSubtaskElementModel {
    /**
     * subtask id
     * @type {number}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    id?: number;
    /**
     * subtask type
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    type?: string;
    /**
     * subtask package
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    _package?: string;
    /**
     * subtask userid
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    userid?: string;
    /**
     * subtask dir
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    dir?: string;
    /**
     * subtask sid
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    sid?: string;
    /**
     * subtask package from
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    pkgFrom?: string;
    /**
     * subtask tag author
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    tagAuthor?: string;
    /**
     * subtask tag id
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    tagId?: string;
    /**
     * subtask tag name
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    tagName?: string;
    /**
     * subtask srpm
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    srpm?: string;
    /**
     * subtask srpm name
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    srpmName?: string;
    /**
     * subtask evr
     * @type {string}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    srpmEvr?: string;
    /**
     * subtask last changed
     * @type {Date}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    lastChanged?: Date;
    /**
     * 
     * @type {TaskInfoPackageModel}
     * @memberof NeedsApprovalSubtaskElementModel
     */
    sourcePackage?: TaskInfoPackageModel;
}

/**
 * Check if a given object implements the NeedsApprovalSubtaskElementModel interface.
 */
export function instanceOfNeedsApprovalSubtaskElementModel(value: object): value is NeedsApprovalSubtaskElementModel {
    return true;
}

export function NeedsApprovalSubtaskElementModelFromJSON(json: any): NeedsApprovalSubtaskElementModel {
    return NeedsApprovalSubtaskElementModelFromJSONTyped(json, false);
}

export function NeedsApprovalSubtaskElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NeedsApprovalSubtaskElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        '_package': json['package'] == null ? undefined : json['package'],
        'userid': json['userid'] == null ? undefined : json['userid'],
        'dir': json['dir'] == null ? undefined : json['dir'],
        'sid': json['sid'] == null ? undefined : json['sid'],
        'pkgFrom': json['pkg_from'] == null ? undefined : json['pkg_from'],
        'tagAuthor': json['tag_author'] == null ? undefined : json['tag_author'],
        'tagId': json['tag_id'] == null ? undefined : json['tag_id'],
        'tagName': json['tag_name'] == null ? undefined : json['tag_name'],
        'srpm': json['srpm'] == null ? undefined : json['srpm'],
        'srpmName': json['srpm_name'] == null ? undefined : json['srpm_name'],
        'srpmEvr': json['srpm_evr'] == null ? undefined : json['srpm_evr'],
        'lastChanged': json['last_changed'] == null ? undefined : (new Date(json['last_changed'])),
        'sourcePackage': json['source_package'] == null ? undefined : TaskInfoPackageModelFromJSON(json['source_package']),
    };
}

export function NeedsApprovalSubtaskElementModelToJSON(value?: NeedsApprovalSubtaskElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'package': value['_package'],
        'userid': value['userid'],
        'dir': value['dir'],
        'sid': value['sid'],
        'pkg_from': value['pkgFrom'],
        'tag_author': value['tagAuthor'],
        'tag_id': value['tagId'],
        'tag_name': value['tagName'],
        'srpm': value['srpm'],
        'srpm_name': value['srpmName'],
        'srpm_evr': value['srpmEvr'],
        'last_changed': value['lastChanged'] == null ? undefined : ((value['lastChanged']).toISOString()),
        'source_package': TaskInfoPackageModelToJSON(value['sourcePackage']),
    };
}

