/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackageMisconflictPackageModel
 */
export interface PackageMisconflictPackageModel {
    /**
     * package name
     * @type {string}
     * @memberof PackageMisconflictPackageModel
     */
    inputPackage?: string;
    /**
     * package name
     * @type {string}
     * @memberof PackageMisconflictPackageModel
     */
    conflictPackage?: string;
    /**
     * package version
     * @type {string}
     * @memberof PackageMisconflictPackageModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof PackageMisconflictPackageModel
     */
    release?: string;
    /**
     * package epoch
     * @type {number}
     * @memberof PackageMisconflictPackageModel
     */
    epoch?: number;
    /**
     * package archs
     * @type {Array<string>}
     * @memberof PackageMisconflictPackageModel
     */
    archs?: Array<string>;
    /**
     * conflict files
     * @type {Array<string>}
     * @memberof PackageMisconflictPackageModel
     */
    filesWithConflict?: Array<string>;
}

/**
 * Check if a given object implements the PackageMisconflictPackageModel interface.
 */
export function instanceOfPackageMisconflictPackageModel(value: object): value is PackageMisconflictPackageModel {
    return true;
}

export function PackageMisconflictPackageModelFromJSON(json: any): PackageMisconflictPackageModel {
    return PackageMisconflictPackageModelFromJSONTyped(json, false);
}

export function PackageMisconflictPackageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageMisconflictPackageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'inputPackage': json['input_package'] == null ? undefined : json['input_package'],
        'conflictPackage': json['conflict_package'] == null ? undefined : json['conflict_package'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'archs': json['archs'] == null ? undefined : json['archs'],
        'filesWithConflict': json['files_with_conflict'] == null ? undefined : json['files_with_conflict'],
    };
}

export function PackageMisconflictPackageModelToJSON(value?: PackageMisconflictPackageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'input_package': value['inputPackage'],
        'conflict_package': value['conflictPackage'],
        'version': value['version'],
        'release': value['release'],
        'epoch': value['epoch'],
        'archs': value['archs'],
        'files_with_conflict': value['filesWithConflict'],
    };
}

