/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackageMisconflictBySrcElementModel
 */
export interface PackageMisconflictBySrcElementModel {
    /**
     * package name
     * @type {string}
     * @memberof PackageMisconflictBySrcElementModel
     */
    inputPackage?: string;
    /**
     * input package archs
     * @type {Array<string>}
     * @memberof PackageMisconflictBySrcElementModel
     */
    inputArchs?: Array<string>;
    /**
     * package name
     * @type {string}
     * @memberof PackageMisconflictBySrcElementModel
     */
    conflictPackage?: string;
    /**
     * package version
     * @type {string}
     * @memberof PackageMisconflictBySrcElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof PackageMisconflictBySrcElementModel
     */
    release?: string;
    /**
     * package epoch
     * @type {number}
     * @memberof PackageMisconflictBySrcElementModel
     */
    epoch?: number;
    /**
     * package archs
     * @type {Array<string>}
     * @memberof PackageMisconflictBySrcElementModel
     */
    archs?: Array<string>;
    /**
     * conflict files
     * @type {Array<string>}
     * @memberof PackageMisconflictBySrcElementModel
     */
    filesWithConflict?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PackageMisconflictBySrcElementModel
     */
    explicit?: boolean;
}

/**
 * Check if a given object implements the PackageMisconflictBySrcElementModel interface.
 */
export function instanceOfPackageMisconflictBySrcElementModel(value: object): value is PackageMisconflictBySrcElementModel {
    return true;
}

export function PackageMisconflictBySrcElementModelFromJSON(json: any): PackageMisconflictBySrcElementModel {
    return PackageMisconflictBySrcElementModelFromJSONTyped(json, false);
}

export function PackageMisconflictBySrcElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageMisconflictBySrcElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'inputPackage': json['input_package'] == null ? undefined : json['input_package'],
        'inputArchs': json['input_archs'] == null ? undefined : json['input_archs'],
        'conflictPackage': json['conflict_package'] == null ? undefined : json['conflict_package'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'archs': json['archs'] == null ? undefined : json['archs'],
        'filesWithConflict': json['files_with_conflict'] == null ? undefined : json['files_with_conflict'],
        'explicit': json['explicit'] == null ? undefined : json['explicit'],
    };
}

export function PackageMisconflictBySrcElementModelToJSON(value?: PackageMisconflictBySrcElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'input_package': value['inputPackage'],
        'input_archs': value['inputArchs'],
        'conflict_package': value['conflictPackage'],
        'version': value['version'],
        'release': value['release'],
        'epoch': value['epoch'],
        'archs': value['archs'],
        'files_with_conflict': value['filesWithConflict'],
        'explicit': value['explicit'],
    };
}

