/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackageByFileNameElementModel } from './PackageByFileNameElementModel';
import {
    PackageByFileNameElementModelFromJSON,
    PackageByFileNameElementModelFromJSONTyped,
    PackageByFileNameElementModelToJSON,
} from './PackageByFileNameElementModel';

/**
 * 
 * @export
 * @interface PackageByFileNameModel
 */
export interface PackageByFileNameModel {
    /**
     * request arguments
     * @type {object}
     * @memberof PackageByFileNameModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof PackageByFileNameModel
     */
    length?: number;
    /**
     * package set packages information
     * @type {Array<PackageByFileNameElementModel>}
     * @memberof PackageByFileNameModel
     */
    packages?: Array<PackageByFileNameElementModel>;
    /**
     * list of not found filenames
     * @type {Array<string>}
     * @memberof PackageByFileNameModel
     */
    notFound?: Array<string>;
}

/**
 * Check if a given object implements the PackageByFileNameModel interface.
 */
export function instanceOfPackageByFileNameModel(value: object): value is PackageByFileNameModel {
    return true;
}

export function PackageByFileNameModelFromJSON(json: any): PackageByFileNameModel {
    return PackageByFileNameModelFromJSONTyped(json, false);
}

export function PackageByFileNameModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageByFileNameModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(PackageByFileNameElementModelFromJSON)),
        'notFound': json['not_found'] == null ? undefined : json['not_found'],
    };
}

export function PackageByFileNameModelToJSON(value?: PackageByFileNameModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(PackageByFileNameElementModelToJSON)),
        'not_found': value['notFound'],
    };
}

