/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackageDependsModel } from './PackageDependsModel';
import {
    PackageDependsModelFromJSON,
    PackageDependsModelFromJSONTyped,
    PackageDependsModelToJSON,
} from './PackageDependsModel';

/**
 * 
 * @export
 * @interface PackageBuildDependencyElementModel
 */
export interface PackageBuildDependencyElementModel {
    /**
     * source package hash UInt64 as string
     * @type {string}
     * @memberof PackageBuildDependencyElementModel
     */
    pkghash?: string;
    /**
     * source package name
     * @type {string}
     * @memberof PackageBuildDependencyElementModel
     */
    name?: string;
    /**
     * package set name
     * @type {string}
     * @memberof PackageBuildDependencyElementModel
     */
    branch?: string;
    /**
     * source package buildtime
     * @type {string}
     * @memberof PackageBuildDependencyElementModel
     */
    buildtime?: string;
    /**
     * package ACL list
     * @type {Array<string>}
     * @memberof PackageBuildDependencyElementModel
     */
    acl?: Array<string>;
    /**
     * package dependencies list
     * @type {Array<PackageDependsModel>}
     * @memberof PackageBuildDependencyElementModel
     */
    depends?: Array<PackageDependsModel>;
}

/**
 * Check if a given object implements the PackageBuildDependencyElementModel interface.
 */
export function instanceOfPackageBuildDependencyElementModel(value: object): value is PackageBuildDependencyElementModel {
    return true;
}

export function PackageBuildDependencyElementModelFromJSON(json: any): PackageBuildDependencyElementModel {
    return PackageBuildDependencyElementModelFromJSONTyped(json, false);
}

export function PackageBuildDependencyElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageBuildDependencyElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pkghash': json['pkghash'] == null ? undefined : json['pkghash'],
        'name': json['name'] == null ? undefined : json['name'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
        'acl': json['acl'] == null ? undefined : json['acl'],
        'depends': json['depends'] == null ? undefined : ((json['depends'] as Array<any>).map(PackageDependsModelFromJSON)),
    };
}

export function PackageBuildDependencyElementModelToJSON(value?: PackageBuildDependencyElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pkghash': value['pkghash'],
        'name': value['name'],
        'branch': value['branch'],
        'buildtime': value['buildtime'],
        'acl': value['acl'],
        'depends': value['depends'] == null ? undefined : ((value['depends'] as Array<any>).map(PackageDependsModelToJSON)),
    };
}

