/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackagesetPackagesElementModel } from './PackagesetPackagesElementModel';
import {
    PackagesetPackagesElementModelFromJSON,
    PackagesetPackagesElementModelFromJSONTyped,
    PackagesetPackagesElementModelToJSON,
} from './PackagesetPackagesElementModel';

/**
 * 
 * @export
 * @interface PackagesetPackagesModel
 */
export interface PackagesetPackagesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof PackagesetPackagesModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof PackagesetPackagesModel
     */
    length?: number;
    /**
     * packages information
     * @type {Array<PackagesetPackagesElementModel>}
     * @memberof PackagesetPackagesModel
     */
    packages?: Array<PackagesetPackagesElementModel>;
}

/**
 * Check if a given object implements the PackagesetPackagesModel interface.
 */
export function instanceOfPackagesetPackagesModel(value: object): value is PackagesetPackagesModel {
    return true;
}

export function PackagesetPackagesModelFromJSON(json: any): PackagesetPackagesModel {
    return PackagesetPackagesModelFromJSONTyped(json, false);
}

export function PackagesetPackagesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackagesetPackagesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(PackagesetPackagesElementModelFromJSON)),
    };
}

export function PackagesetPackagesModelToJSON(value?: PackagesetPackagesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(PackagesetPackagesElementModelToJSON)),
    };
}

