/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackageBuildDependencyElementModel } from './PackageBuildDependencyElementModel';
import {
    PackageBuildDependencyElementModelFromJSON,
    PackageBuildDependencyElementModelFromJSONTyped,
    PackageBuildDependencyElementModelToJSON,
} from './PackageBuildDependencyElementModel';

/**
 * 
 * @export
 * @interface PackageBuildDependencyModel
 */
export interface PackageBuildDependencyModel {
    /**
     * request arguments
     * @type {object}
     * @memberof PackageBuildDependencyModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof PackageBuildDependencyModel
     */
    length?: number;
    /**
     * build dependency results
     * @type {Array<PackageBuildDependencyElementModel>}
     * @memberof PackageBuildDependencyModel
     */
    dependencies?: Array<PackageBuildDependencyElementModel>;
}

/**
 * Check if a given object implements the PackageBuildDependencyModel interface.
 */
export function instanceOfPackageBuildDependencyModel(value: object): value is PackageBuildDependencyModel {
    return true;
}

export function PackageBuildDependencyModelFromJSON(json: any): PackageBuildDependencyModel {
    return PackageBuildDependencyModelFromJSONTyped(json, false);
}

export function PackageBuildDependencyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageBuildDependencyModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'dependencies': json['dependencies'] == null ? undefined : ((json['dependencies'] as Array<any>).map(PackageBuildDependencyElementModelFromJSON)),
    };
}

export function PackageBuildDependencyModelToJSON(value?: PackageBuildDependencyModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'dependencies': value['dependencies'] == null ? undefined : ((value['dependencies'] as Array<any>).map(PackageBuildDependencyElementModelToJSON)),
    };
}

