/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackageNameFromRepologyModel
 */
export interface PackageNameFromRepologyModel {
    /**
     * request arguments
     * @type {object}
     * @memberof PackageNameFromRepologyModel
     */
    requestArgs?: object;
    /**
     * package name from repology
     * @type {string}
     * @memberof PackageNameFromRepologyModel
     */
    name?: string;
    /**
     * repository name from repology
     * @type {string}
     * @memberof PackageNameFromRepologyModel
     */
    repo?: string;
}

/**
 * Check if a given object implements the PackageNameFromRepologyModel interface.
 */
export function instanceOfPackageNameFromRepologyModel(value: object): value is PackageNameFromRepologyModel {
    return true;
}

export function PackageNameFromRepologyModelFromJSON(json: any): PackageNameFromRepologyModel {
    return PackageNameFromRepologyModelFromJSONTyped(json, false);
}

export function PackageNameFromRepologyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageNameFromRepologyModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'name': json['name'] == null ? undefined : json['name'],
        'repo': json['repo'] == null ? undefined : json['repo'],
    };
}

export function PackageNameFromRepologyModelToJSON(value?: PackageNameFromRepologyModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'name': value['name'],
        'repo': value['repo'],
    };
}

