/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackagesetCompareElementModel } from './PackagesetCompareElementModel';
import {
    PackagesetCompareElementModelFromJSON,
    PackagesetCompareElementModelFromJSONTyped,
    PackagesetCompareElementModelToJSON,
} from './PackagesetCompareElementModel';

/**
 * 
 * @export
 * @interface PackagesetCompareModel
 */
export interface PackagesetCompareModel {
    /**
     * request arguments
     * @type {object}
     * @memberof PackagesetCompareModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof PackagesetCompareModel
     */
    length?: number;
    /**
     * packages information
     * @type {Array<PackagesetCompareElementModel>}
     * @memberof PackagesetCompareModel
     */
    packages?: Array<PackagesetCompareElementModel>;
}

/**
 * Check if a given object implements the PackagesetCompareModel interface.
 */
export function instanceOfPackagesetCompareModel(value: object): value is PackagesetCompareModel {
    return true;
}

export function PackagesetCompareModelFromJSON(json: any): PackagesetCompareModel {
    return PackagesetCompareModelFromJSONTyped(json, false);
}

export function PackagesetCompareModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackagesetCompareModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(PackagesetCompareElementModelFromJSON)),
    };
}

export function PackagesetCompareModelToJSON(value?: PackagesetCompareModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(PackagesetCompareElementModelToJSON)),
    };
}

