/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackageFindPackagesetElementModel } from './PackageFindPackagesetElementModel';
import {
    PackageFindPackagesetElementModelFromJSON,
    PackageFindPackagesetElementModelFromJSONTyped,
    PackageFindPackagesetElementModelToJSON,
} from './PackageFindPackagesetElementModel';

/**
 * 
 * @export
 * @interface PackageFindPackagesetModel
 */
export interface PackageFindPackagesetModel {
    /**
     * request arguments
     * @type {object}
     * @memberof PackageFindPackagesetModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof PackageFindPackagesetModel
     */
    length?: number;
    /**
     * package set packages information
     * @type {Array<PackageFindPackagesetElementModel>}
     * @memberof PackageFindPackagesetModel
     */
    packages?: Array<PackageFindPackagesetElementModel>;
}

/**
 * Check if a given object implements the PackageFindPackagesetModel interface.
 */
export function instanceOfPackageFindPackagesetModel(value: object): value is PackageFindPackagesetModel {
    return true;
}

export function PackageFindPackagesetModelFromJSON(json: any): PackageFindPackagesetModel {
    return PackageFindPackagesetModelFromJSONTyped(json, false);
}

export function PackageFindPackagesetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageFindPackagesetModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(PackageFindPackagesetElementModelFromJSON)),
    };
}

export function PackageFindPackagesetModelToJSON(value?: PackageFindPackagesetModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(PackageFindPackagesetElementModelToJSON)),
    };
}

