/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackagesetPackagesElementModel
 */
export interface PackagesetPackagesElementModel {
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    hash?: string;
    /**
     * package name
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    release?: string;
    /**
     * package summary
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    summary?: string;
    /**
     * package url
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    url?: string;
    /**
     * package license
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    license?: string;
    /**
     * package category
     * @type {string}
     * @memberof PackagesetPackagesElementModel
     */
    category?: string;
    /**
     * package maintainers
     * @type {Array<string>}
     * @memberof PackagesetPackagesElementModel
     */
    maintainers?: Array<string>;
    /**
     * package ACL list
     * @type {Array<string>}
     * @memberof PackagesetPackagesElementModel
     */
    aclList?: Array<string>;
    /**
     * package archs
     * @type {Array<string>}
     * @memberof PackagesetPackagesElementModel
     */
    archs?: Array<string>;
}

/**
 * Check if a given object implements the PackagesetPackagesElementModel interface.
 */
export function instanceOfPackagesetPackagesElementModel(value: object): value is PackagesetPackagesElementModel {
    return true;
}

export function PackagesetPackagesElementModelFromJSON(json: any): PackagesetPackagesElementModel {
    return PackagesetPackagesElementModelFromJSONTyped(json, false);
}

export function PackagesetPackagesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackagesetPackagesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'] == null ? undefined : json['hash'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'url': json['url'] == null ? undefined : json['url'],
        'license': json['license'] == null ? undefined : json['license'],
        'category': json['category'] == null ? undefined : json['category'],
        'maintainers': json['maintainers'] == null ? undefined : json['maintainers'],
        'aclList': json['acl_list'] == null ? undefined : json['acl_list'],
        'archs': json['archs'] == null ? undefined : json['archs'],
    };
}

export function PackagesetPackagesElementModelToJSON(value?: PackagesetPackagesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': value['hash'],
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'summary': value['summary'],
        'url': value['url'],
        'license': value['license'],
        'category': value['category'],
        'maintainers': value['maintainers'],
        'acl_list': value['aclList'],
        'archs': value['archs'],
    };
}

