/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackageDependsElementModel } from './PackageDependsElementModel';
import {
    PackageDependsElementModelFromJSON,
    PackageDependsElementModelFromJSONTyped,
    PackageDependsElementModelToJSON,
} from './PackageDependsElementModel';

/**
 * 
 * @export
 * @interface PackageDependsModel
 */
export interface PackageDependsModel {
    /**
     * package requirements
     * @type {PackageDependsElementModel}
     * @memberof PackageDependsModel
     */
    requires?: PackageDependsElementModel;
    /**
     * package provides
     * @type {PackageDependsElementModel}
     * @memberof PackageDependsModel
     */
    provides?: PackageDependsElementModel;
}

/**
 * Check if a given object implements the PackageDependsModel interface.
 */
export function instanceOfPackageDependsModel(value: object): value is PackageDependsModel {
    return true;
}

export function PackageDependsModelFromJSON(json: any): PackageDependsModel {
    return PackageDependsModelFromJSONTyped(json, false);
}

export function PackageDependsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageDependsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requires': json['requires'] == null ? undefined : PackageDependsElementModelFromJSON(json['requires']),
        'provides': json['provides'] == null ? undefined : PackageDependsElementModelFromJSON(json['provides']),
    };
}

export function PackageDependsModelToJSON(value?: PackageDependsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'requires': PackageDependsElementModelToJSON(value['requires']),
        'provides': PackageDependsElementModelToJSON(value['provides']),
    };
}

