/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackageSpecfileModel
 */
export interface PackageSpecfileModel {
    /**
     * request arguments
     * @type {object}
     * @memberof PackageSpecfileModel
     */
    requestArgs?: object;
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof PackageSpecfileModel
     */
    pkgHash?: string;
    /**
     * source package name
     * @type {string}
     * @memberof PackageSpecfileModel
     */
    pkgName?: string;
    /**
     * source package version
     * @type {string}
     * @memberof PackageSpecfileModel
     */
    pkgVersion?: string;
    /**
     * source package release
     * @type {string}
     * @memberof PackageSpecfileModel
     */
    pkgRelease?: string;
    /**
     * spec file name
     * @type {string}
     * @memberof PackageSpecfileModel
     */
    specfileName?: string;
    /**
     * spec file mtime
     * @type {string}
     * @memberof PackageSpecfileModel
     */
    specfileDate?: string;
    /**
     * spec file base64 encoded raw contents
     * @type {string}
     * @memberof PackageSpecfileModel
     */
    specfileContent?: string;
}

/**
 * Check if a given object implements the PackageSpecfileModel interface.
 */
export function instanceOfPackageSpecfileModel(value: object): value is PackageSpecfileModel {
    return true;
}

export function PackageSpecfileModelFromJSON(json: any): PackageSpecfileModel {
    return PackageSpecfileModelFromJSONTyped(json, false);
}

export function PackageSpecfileModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageSpecfileModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'pkgHash': json['pkg_hash'] == null ? undefined : json['pkg_hash'],
        'pkgName': json['pkg_name'] == null ? undefined : json['pkg_name'],
        'pkgVersion': json['pkg_version'] == null ? undefined : json['pkg_version'],
        'pkgRelease': json['pkg_release'] == null ? undefined : json['pkg_release'],
        'specfileName': json['specfile_name'] == null ? undefined : json['specfile_name'],
        'specfileDate': json['specfile_date'] == null ? undefined : json['specfile_date'],
        'specfileContent': json['specfile_content'] == null ? undefined : json['specfile_content'],
    };
}

export function PackageSpecfileModelToJSON(value?: PackageSpecfileModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'pkg_hash': value['pkgHash'],
        'pkg_name': value['pkgName'],
        'pkg_version': value['pkgVersion'],
        'pkg_release': value['pkgRelease'],
        'specfile_name': value['specfileName'],
        'specfile_date': value['specfileDate'],
        'specfile_content': value['specfileContent'],
    };
}

