/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepocopJsonGetModel
 */
export interface RepocopJsonGetModel {
    /**
     * package name
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    pkgName?: string;
    /**
     * package version
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    pkgVersion?: string;
    /**
     * package release
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    pkgRelease?: string;
    /**
     * package arch
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    pkgArch?: string;
    /**
     * package branch
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    branch?: string;
    /**
     * repocop test name
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    testName?: string;
    /**
     * repocop test status
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    testStatus?: string;
    /**
     * repocop test message
     * @type {string}
     * @memberof RepocopJsonGetModel
     */
    testMessage?: string;
    /**
     * repocop test date
     * @type {Date}
     * @memberof RepocopJsonGetModel
     */
    testDate?: Date;
}

/**
 * Check if a given object implements the RepocopJsonGetModel interface.
 */
export function instanceOfRepocopJsonGetModel(value: object): value is RepocopJsonGetModel {
    return true;
}

export function RepocopJsonGetModelFromJSON(json: any): RepocopJsonGetModel {
    return RepocopJsonGetModelFromJSONTyped(json, false);
}

export function RepocopJsonGetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepocopJsonGetModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pkgName': json['pkg_name'] == null ? undefined : json['pkg_name'],
        'pkgVersion': json['pkg_version'] == null ? undefined : json['pkg_version'],
        'pkgRelease': json['pkg_release'] == null ? undefined : json['pkg_release'],
        'pkgArch': json['pkg_arch'] == null ? undefined : json['pkg_arch'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'testName': json['test_name'] == null ? undefined : json['test_name'],
        'testStatus': json['test_status'] == null ? undefined : json['test_status'],
        'testMessage': json['test_message'] == null ? undefined : json['test_message'],
        'testDate': json['test_date'] == null ? undefined : (new Date(json['test_date'])),
    };
}

export function RepocopJsonGetModelToJSON(value?: RepocopJsonGetModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pkg_name': value['pkgName'],
        'pkg_version': value['pkgVersion'],
        'pkg_release': value['pkgRelease'],
        'pkg_arch': value['pkgArch'],
        'branch': value['branch'],
        'test_name': value['testName'],
        'test_status': value['testStatus'],
        'test_message': value['testMessage'],
        'test_date': value['testDate'] == null ? undefined : ((value['testDate']).toISOString()),
    };
}

