/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositoryStatisticsBranchesModel } from './RepositoryStatisticsBranchesModel';
import {
    RepositoryStatisticsBranchesModelFromJSON,
    RepositoryStatisticsBranchesModelFromJSONTyped,
    RepositoryStatisticsBranchesModelToJSON,
} from './RepositoryStatisticsBranchesModel';

/**
 * 
 * @export
 * @interface RepositoryStatisticsModel
 */
export interface RepositoryStatisticsModel {
    /**
     * number of packages found
     * @type {number}
     * @memberof RepositoryStatisticsModel
     */
    length?: number;
    /**
     * list of branches with packages count
     * @type {Array<RepositoryStatisticsBranchesModel>}
     * @memberof RepositoryStatisticsModel
     */
    branches?: Array<RepositoryStatisticsBranchesModel>;
}

/**
 * Check if a given object implements the RepositoryStatisticsModel interface.
 */
export function instanceOfRepositoryStatisticsModel(value: object): value is RepositoryStatisticsModel {
    return true;
}

export function RepositoryStatisticsModelFromJSON(json: any): RepositoryStatisticsModel {
    return RepositoryStatisticsModelFromJSONTyped(json, false);
}

export function RepositoryStatisticsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepositoryStatisticsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(RepositoryStatisticsBranchesModelFromJSON)),
    };
}

export function RepositoryStatisticsModelToJSON(value?: RepositoryStatisticsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(RepositoryStatisticsBranchesModelToJSON)),
    };
}

