/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepocopJsonPostModel
 */
export interface RepocopJsonPostModel {
    /**
     * package name
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    pkgName: string;
    /**
     * package version
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    pkgVersion: string;
    /**
     * package release
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    pkgRelease: string;
    /**
     * package arch
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    pkgArch: string;
    /**
     * package branch
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    pkgsetName: string;
    /**
     * source package name
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    rcSrcpkgName: string;
    /**
     * source package version
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    rcSrcpkgVersion: string;
    /**
     * source package version
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    rcSrcpkgRelease: string;
    /**
     * repocop test name
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    rcTestName: string;
    /**
     * repocop test status
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    rcTestStatus: string;
    /**
     * repocop test message
     * @type {string}
     * @memberof RepocopJsonPostModel
     */
    rcTestMessage: string;
    /**
     * repocop test date
     * @type {Date}
     * @memberof RepocopJsonPostModel
     */
    rcTestDate: Date;
}

/**
 * Check if a given object implements the RepocopJsonPostModel interface.
 */
export function instanceOfRepocopJsonPostModel(value: object): value is RepocopJsonPostModel {
    if (!('pkgName' in value) || value['pkgName'] === undefined) return false;
    if (!('pkgVersion' in value) || value['pkgVersion'] === undefined) return false;
    if (!('pkgRelease' in value) || value['pkgRelease'] === undefined) return false;
    if (!('pkgArch' in value) || value['pkgArch'] === undefined) return false;
    if (!('pkgsetName' in value) || value['pkgsetName'] === undefined) return false;
    if (!('rcSrcpkgName' in value) || value['rcSrcpkgName'] === undefined) return false;
    if (!('rcSrcpkgVersion' in value) || value['rcSrcpkgVersion'] === undefined) return false;
    if (!('rcSrcpkgRelease' in value) || value['rcSrcpkgRelease'] === undefined) return false;
    if (!('rcTestName' in value) || value['rcTestName'] === undefined) return false;
    if (!('rcTestStatus' in value) || value['rcTestStatus'] === undefined) return false;
    if (!('rcTestMessage' in value) || value['rcTestMessage'] === undefined) return false;
    if (!('rcTestDate' in value) || value['rcTestDate'] === undefined) return false;
    return true;
}

export function RepocopJsonPostModelFromJSON(json: any): RepocopJsonPostModel {
    return RepocopJsonPostModelFromJSONTyped(json, false);
}

export function RepocopJsonPostModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepocopJsonPostModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pkgName': json['pkg_name'],
        'pkgVersion': json['pkg_version'],
        'pkgRelease': json['pkg_release'],
        'pkgArch': json['pkg_arch'],
        'pkgsetName': json['pkgset_name'],
        'rcSrcpkgName': json['rc_srcpkg_name'],
        'rcSrcpkgVersion': json['rc_srcpkg_version'],
        'rcSrcpkgRelease': json['rc_srcpkg_release'],
        'rcTestName': json['rc_test_name'],
        'rcTestStatus': json['rc_test_status'],
        'rcTestMessage': json['rc_test_message'],
        'rcTestDate': (new Date(json['rc_test_date'])),
    };
}

export function RepocopJsonPostModelToJSON(value?: RepocopJsonPostModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pkg_name': value['pkgName'],
        'pkg_version': value['pkgVersion'],
        'pkg_release': value['pkgRelease'],
        'pkg_arch': value['pkgArch'],
        'pkgset_name': value['pkgsetName'],
        'rc_srcpkg_name': value['rcSrcpkgName'],
        'rc_srcpkg_version': value['rcSrcpkgVersion'],
        'rc_srcpkg_release': value['rcSrcpkgRelease'],
        'rc_test_name': value['rcTestName'],
        'rc_test_status': value['rcTestStatus'],
        'rc_test_message': value['rcTestMessage'],
        'rc_test_date': ((value['rcTestDate']).toISOString()),
    };
}

