/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteTaskByNameTaskModel } from './SiteTaskByNameTaskModel';
import {
    SiteTaskByNameTaskModelFromJSON,
    SiteTaskByNameTaskModelFromJSONTyped,
    SiteTaskByNameTaskModelToJSON,
} from './SiteTaskByNameTaskModel';

/**
 * 
 * @export
 * @interface SiteTaskByNameModel
 */
export interface SiteTaskByNameModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SiteTaskByNameModel
     */
    requestArgs?: object;
    /**
     * number of tasks found
     * @type {number}
     * @memberof SiteTaskByNameModel
     */
    length?: number;
    /**
     * tasks list
     * @type {Array<SiteTaskByNameTaskModel>}
     * @memberof SiteTaskByNameModel
     */
    tasks?: Array<SiteTaskByNameTaskModel>;
}

/**
 * Check if a given object implements the SiteTaskByNameModel interface.
 */
export function instanceOfSiteTaskByNameModel(value: object): value is SiteTaskByNameModel {
    return true;
}

export function SiteTaskByNameModelFromJSON(json: any): SiteTaskByNameModel {
    return SiteTaskByNameModelFromJSONTyped(json, false);
}

export function SiteTaskByNameModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteTaskByNameModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(SiteTaskByNameTaskModelFromJSON)),
    };
}

export function SiteTaskByNameModelToJSON(value?: SiteTaskByNameModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(SiteTaskByNameTaskModelToJSON)),
    };
}

