/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteAllArchsElementModel } from './SiteAllArchsElementModel';
import {
    SiteAllArchsElementModelFromJSON,
    SiteAllArchsElementModelFromJSONTyped,
    SiteAllArchsElementModelToJSON,
} from './SiteAllArchsElementModel';

/**
 * 
 * @export
 * @interface SiteAllArchsModel
 */
export interface SiteAllArchsModel {
    /**
     * number of binary package archs and source packages count
     * @type {number}
     * @memberof SiteAllArchsModel
     */
    length?: number;
    /**
     * binary package archs
     * @type {Array<SiteAllArchsElementModel>}
     * @memberof SiteAllArchsModel
     */
    archs?: Array<SiteAllArchsElementModel>;
}

/**
 * Check if a given object implements the SiteAllArchsModel interface.
 */
export function instanceOfSiteAllArchsModel(value: object): value is SiteAllArchsModel {
    return true;
}

export function SiteAllArchsModelFromJSON(json: any): SiteAllArchsModel {
    return SiteAllArchsModelFromJSONTyped(json, false);
}

export function SiteAllArchsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteAllArchsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'archs': json['archs'] == null ? undefined : ((json['archs'] as Array<any>).map(SiteAllArchsElementModelFromJSON)),
    };
}

export function SiteAllArchsModelToJSON(value?: SiteAllArchsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
        'archs': value['archs'] == null ? undefined : ((value['archs'] as Array<any>).map(SiteAllArchsElementModelToJSON)),
    };
}

