/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitemapPackagesElementModel
 */
export interface SitemapPackagesElementModel {
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof SitemapPackagesElementModel
     */
    pkghash?: string;
    /**
     * package name
     * @type {string}
     * @memberof SitemapPackagesElementModel
     */
    name?: string;
    /**
     * package buildtime
     * @type {number}
     * @memberof SitemapPackagesElementModel
     */
    buildtime?: number;
}

/**
 * Check if a given object implements the SitemapPackagesElementModel interface.
 */
export function instanceOfSitemapPackagesElementModel(value: object): value is SitemapPackagesElementModel {
    return true;
}

export function SitemapPackagesElementModelFromJSON(json: any): SitemapPackagesElementModel {
    return SitemapPackagesElementModelFromJSONTyped(json, false);
}

export function SitemapPackagesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitemapPackagesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pkghash': json['pkghash'] == null ? undefined : json['pkghash'],
        'name': json['name'] == null ? undefined : json['name'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
    };
}

export function SitemapPackagesElementModelToJSON(value?: SitemapPackagesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pkghash': value['pkghash'],
        'name': value['name'],
        'buildtime': value['buildtime'],
    };
}

