/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteLastPackagesWithCVEFixesElementModel
 */
export interface SiteLastPackagesWithCVEFixesElementModel {
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    hash?: string;
    /**
     * package name
     * @type {string}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    release?: string;
    /**
     * package summary
     * @type {string}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    summary?: string;
    /**
     * package buildtime
     * @type {number}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    buildtime?: number;
    /**
     * package last changelog date (ISO 8601 format)
     * @type {string}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    changelogDate?: string;
    /**
     * package last changelog text
     * @type {string}
     * @memberof SiteLastPackagesWithCVEFixesElementModel
     */
    changelogText?: string;
}

/**
 * Check if a given object implements the SiteLastPackagesWithCVEFixesElementModel interface.
 */
export function instanceOfSiteLastPackagesWithCVEFixesElementModel(value: object): value is SiteLastPackagesWithCVEFixesElementModel {
    return true;
}

export function SiteLastPackagesWithCVEFixesElementModelFromJSON(json: any): SiteLastPackagesWithCVEFixesElementModel {
    return SiteLastPackagesWithCVEFixesElementModelFromJSONTyped(json, false);
}

export function SiteLastPackagesWithCVEFixesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteLastPackagesWithCVEFixesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'] == null ? undefined : json['hash'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
        'changelogDate': json['changelog_date'] == null ? undefined : json['changelog_date'],
        'changelogText': json['changelog_text'] == null ? undefined : json['changelog_text'],
    };
}

export function SiteLastPackagesWithCVEFixesElementModelToJSON(value?: SiteLastPackagesWithCVEFixesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': value['hash'],
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'summary': value['summary'],
        'buildtime': value['buildtime'],
        'changelog_date': value['changelogDate'],
        'changelog_text': value['changelogText'],
    };
}

