/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteLastBranchPackagesPackageModel } from './SiteLastBranchPackagesPackageModel';
import {
    SiteLastBranchPackagesPackageModelFromJSON,
    SiteLastBranchPackagesPackageModelFromJSONTyped,
    SiteLastBranchPackagesPackageModelToJSON,
} from './SiteLastBranchPackagesPackageModel';

/**
 * 
 * @export
 * @interface SiteLastBranchPackagesModel
 */
export interface SiteLastBranchPackagesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SiteLastBranchPackagesModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof SiteLastBranchPackagesModel
     */
    length?: number;
    /**
     * last packages list
     * @type {Array<SiteLastBranchPackagesPackageModel>}
     * @memberof SiteLastBranchPackagesModel
     */
    packages?: Array<SiteLastBranchPackagesPackageModel>;
    /**
     * last loaded branch date
     * @type {string}
     * @memberof SiteLastBranchPackagesModel
     */
    lastBranchDate?: string;
}

/**
 * Check if a given object implements the SiteLastBranchPackagesModel interface.
 */
export function instanceOfSiteLastBranchPackagesModel(value: object): value is SiteLastBranchPackagesModel {
    return true;
}

export function SiteLastBranchPackagesModelFromJSON(json: any): SiteLastBranchPackagesModel {
    return SiteLastBranchPackagesModelFromJSONTyped(json, false);
}

export function SiteLastBranchPackagesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteLastBranchPackagesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(SiteLastBranchPackagesPackageModelFromJSON)),
        'lastBranchDate': json['last_branch_date'] == null ? undefined : json['last_branch_date'],
    };
}

export function SiteLastBranchPackagesModelToJSON(value?: SiteLastBranchPackagesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(SiteLastBranchPackagesPackageModelToJSON)),
        'last_branch_date': value['lastBranchDate'],
    };
}

