/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteLastPackagesElementModel
 */
export interface SiteLastPackagesElementModel {
    /**
     * subtask id
     * @type {number}
     * @memberof SiteLastPackagesElementModel
     */
    subtaskId?: number;
    /**
     * subtask created by
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    subtaskUserid?: string;
    /**
     * subtask type [build|rebuild|delete]
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    subtaskType?: string;
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    hash?: string;
    /**
     * package name
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    release?: string;
    /**
     * package summary
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    summary?: string;
    /**
     * package buildtime
     * @type {number}
     * @memberof SiteLastPackagesElementModel
     */
    buildtime?: number;
    /**
     * package last changelog name
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    changelogName?: string;
    /**
     * package last changelog nickname
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    changelogNickname?: string;
    /**
     * package last changelog message date
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    changelogDate?: string;
    /**
     * package last changelog message
     * @type {string}
     * @memberof SiteLastPackagesElementModel
     */
    changelogText?: string;
}

/**
 * Check if a given object implements the SiteLastPackagesElementModel interface.
 */
export function instanceOfSiteLastPackagesElementModel(value: object): value is SiteLastPackagesElementModel {
    return true;
}

export function SiteLastPackagesElementModelFromJSON(json: any): SiteLastPackagesElementModel {
    return SiteLastPackagesElementModelFromJSONTyped(json, false);
}

export function SiteLastPackagesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteLastPackagesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'subtaskId': json['subtask_id'] == null ? undefined : json['subtask_id'],
        'subtaskUserid': json['subtask_userid'] == null ? undefined : json['subtask_userid'],
        'subtaskType': json['subtask_type'] == null ? undefined : json['subtask_type'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
        'changelogName': json['changelog_name'] == null ? undefined : json['changelog_name'],
        'changelogNickname': json['changelog_nickname'] == null ? undefined : json['changelog_nickname'],
        'changelogDate': json['changelog_date'] == null ? undefined : json['changelog_date'],
        'changelogText': json['changelog_text'] == null ? undefined : json['changelog_text'],
    };
}

export function SiteLastPackagesElementModelToJSON(value?: SiteLastPackagesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'subtask_id': value['subtaskId'],
        'subtask_userid': value['subtaskUserid'],
        'subtask_type': value['subtaskType'],
        'hash': value['hash'],
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'summary': value['summary'],
        'buildtime': value['buildtime'],
        'changelog_name': value['changelogName'],
        'changelog_nickname': value['changelogNickname'],
        'changelog_date': value['changelogDate'],
        'changelog_text': value['changelogText'],
    };
}

