/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteBeehiveByMaintainerElementModel
 */
export interface SiteBeehiveByMaintainerElementModel {
    /**
     * Beehive branch
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    branch?: string;
    /**
     * package name
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    release?: string;
    /**
     * Beehive arch
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    arch?: string;
    /**
     * Beehive rebuild date
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    updated?: string;
    /**
     * Package FTBFS since date
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    ftbfsSince?: string;
    /**
     * Beehive package build elapsed (seconds)
     * @type {number}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    buildTime?: number;
    /**
     * Beehive package build error log URL
     * @type {string}
     * @memberof SiteBeehiveByMaintainerElementModel
     */
    url?: string;
}

/**
 * Check if a given object implements the SiteBeehiveByMaintainerElementModel interface.
 */
export function instanceOfSiteBeehiveByMaintainerElementModel(value: object): value is SiteBeehiveByMaintainerElementModel {
    return true;
}

export function SiteBeehiveByMaintainerElementModelFromJSON(json: any): SiteBeehiveByMaintainerElementModel {
    return SiteBeehiveByMaintainerElementModelFromJSONTyped(json, false);
}

export function SiteBeehiveByMaintainerElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteBeehiveByMaintainerElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'arch': json['arch'] == null ? undefined : json['arch'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'ftbfsSince': json['ftbfs_since'] == null ? undefined : json['ftbfs_since'],
        'buildTime': json['build_time'] == null ? undefined : json['build_time'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function SiteBeehiveByMaintainerElementModelToJSON(value?: SiteBeehiveByMaintainerElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'branch': value['branch'],
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'arch': value['arch'],
        'updated': value['updated'],
        'ftbfs_since': value['ftbfsSince'],
        'build_time': value['buildTime'],
        'url': value['url'],
    };
}

