/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitePackagesElementModel
 */
export interface SitePackagesElementModel {
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    hash?: string;
    /**
     * package name
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    release?: string;
    /**
     * package summary
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    summary?: string;
    /**
     * package buildtime
     * @type {number}
     * @memberof SitePackagesElementModel
     */
    buildtime?: number;
    /**
     * package category
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    category?: string;
    /**
     * package maintainer
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    maintainer?: string;
    /**
     * package last changelog message
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    changelog?: string;
    /**
     * package build task id
     * @type {number}
     * @memberof SitePackagesElementModel
     */
    taskId?: number;
    /**
     * package build subtask id
     * @type {number}
     * @memberof SitePackagesElementModel
     */
    subtaskId?: number;
    /**
     * package build task owner
     * @type {string}
     * @memberof SitePackagesElementModel
     */
    taskOwner?: string;
}

/**
 * Check if a given object implements the SitePackagesElementModel interface.
 */
export function instanceOfSitePackagesElementModel(value: object): value is SitePackagesElementModel {
    return true;
}

export function SitePackagesElementModelFromJSON(json: any): SitePackagesElementModel {
    return SitePackagesElementModelFromJSONTyped(json, false);
}

export function SitePackagesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitePackagesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'] == null ? undefined : json['hash'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
        'category': json['category'] == null ? undefined : json['category'],
        'maintainer': json['maintainer'] == null ? undefined : json['maintainer'],
        'changelog': json['changelog'] == null ? undefined : json['changelog'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'subtaskId': json['subtask_id'] == null ? undefined : json['subtask_id'],
        'taskOwner': json['task_owner'] == null ? undefined : json['task_owner'],
    };
}

export function SitePackagesElementModelToJSON(value?: SitePackagesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': value['hash'],
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'summary': value['summary'],
        'buildtime': value['buildtime'],
        'category': value['category'],
        'maintainer': value['maintainer'],
        'changelog': value['changelog'],
        'task_id': value['taskId'],
        'subtask_id': value['subtaskId'],
        'task_owner': value['taskOwner'],
    };
}

