/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteFastPackagesSearchElementModel } from './SiteFastPackagesSearchElementModel';
import {
    SiteFastPackagesSearchElementModelFromJSON,
    SiteFastPackagesSearchElementModelFromJSONTyped,
    SiteFastPackagesSearchElementModelToJSON,
} from './SiteFastPackagesSearchElementModel';

/**
 * 
 * @export
 * @interface SiteFastPackagesSearchModel
 */
export interface SiteFastPackagesSearchModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SiteFastPackagesSearchModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof SiteFastPackagesSearchModel
     */
    length?: number;
    /**
     * list of found packages
     * @type {Array<SiteFastPackagesSearchElementModel>}
     * @memberof SiteFastPackagesSearchModel
     */
    packages?: Array<SiteFastPackagesSearchElementModel>;
}

/**
 * Check if a given object implements the SiteFastPackagesSearchModel interface.
 */
export function instanceOfSiteFastPackagesSearchModel(value: object): value is SiteFastPackagesSearchModel {
    return true;
}

export function SiteFastPackagesSearchModelFromJSON(json: any): SiteFastPackagesSearchModel {
    return SiteFastPackagesSearchModelFromJSONTyped(json, false);
}

export function SiteFastPackagesSearchModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteFastPackagesSearchModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(SiteFastPackagesSearchElementModelFromJSON)),
    };
}

export function SiteFastPackagesSearchModelToJSON(value?: SiteFastPackagesSearchModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(SiteFastPackagesSearchElementModelToJSON)),
    };
}

