/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SitePackagesElementModel } from './SitePackagesElementModel';
import {
    SitePackagesElementModelFromJSON,
    SitePackagesElementModelFromJSONTyped,
    SitePackagesElementModelToJSON,
} from './SitePackagesElementModel';

/**
 * 
 * @export
 * @interface SitePackagesModel
 */
export interface SitePackagesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SitePackagesModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof SitePackagesModel
     */
    length?: number;
    /**
     * list of subcategories
     * @type {Array<string>}
     * @memberof SitePackagesModel
     */
    subcategories?: Array<string>;
    /**
     * unpackaged directories information
     * @type {Array<SitePackagesElementModel>}
     * @memberof SitePackagesModel
     */
    packages?: Array<SitePackagesElementModel>;
}

/**
 * Check if a given object implements the SitePackagesModel interface.
 */
export function instanceOfSitePackagesModel(value: object): value is SitePackagesModel {
    return true;
}

export function SitePackagesModelFromJSON(json: any): SitePackagesModel {
    return SitePackagesModelFromJSONTyped(json, false);
}

export function SitePackagesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitePackagesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'subcategories': json['subcategories'] == null ? undefined : json['subcategories'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(SitePackagesElementModelFromJSON)),
    };
}

export function SitePackagesModelToJSON(value?: SitePackagesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'subcategories': value['subcategories'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(SitePackagesElementModelToJSON)),
    };
}

