/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitePackagesetStatusElementModel
 */
export interface SitePackagesetStatusElementModel {
    /**
     * package set name
     * @type {string}
     * @memberof SitePackagesetStatusElementModel
     */
    branch?: string;
    /**
     * support start date
     * @type {Date}
     * @memberof SitePackagesetStatusElementModel
     */
    startDate?: Date;
    /**
     * support end date
     * @type {Date}
     * @memberof SitePackagesetStatusElementModel
     */
    endDate?: Date;
    /**
     * 0 - hide branch, 1 - show branch
     * @type {number}
     * @memberof SitePackagesetStatusElementModel
     */
    show?: number;
    /**
     * html description in Russian
     * @type {string}
     * @memberof SitePackagesetStatusElementModel
     */
    descriptionRu?: string;
    /**
     * html description in English
     * @type {string}
     * @memberof SitePackagesetStatusElementModel
     */
    descriptionEn?: string;
    /**
     * 0 - branch has no active images, 1 - branch has active images
     * @type {number}
     * @memberof SitePackagesetStatusElementModel
     */
    hasImages?: number;
}

/**
 * Check if a given object implements the SitePackagesetStatusElementModel interface.
 */
export function instanceOfSitePackagesetStatusElementModel(value: object): value is SitePackagesetStatusElementModel {
    return true;
}

export function SitePackagesetStatusElementModelFromJSON(json: any): SitePackagesetStatusElementModel {
    return SitePackagesetStatusElementModelFromJSONTyped(json, false);
}

export function SitePackagesetStatusElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitePackagesetStatusElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'show': json['show'] == null ? undefined : json['show'],
        'descriptionRu': json['description_ru'] == null ? undefined : json['description_ru'],
        'descriptionEn': json['description_en'] == null ? undefined : json['description_en'],
        'hasImages': json['has_images'] == null ? undefined : json['has_images'],
    };
}

export function SitePackagesetStatusElementModelToJSON(value?: SitePackagesetStatusElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'branch': value['branch'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'show': value['show'],
        'description_ru': value['descriptionRu'],
        'description_en': value['descriptionEn'],
        'has_images': value['hasImages'],
    };
}

