/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteLastPackagesPackageModel } from './SiteLastPackagesPackageModel';
import {
    SiteLastPackagesPackageModelFromJSON,
    SiteLastPackagesPackageModelFromJSONTyped,
    SiteLastPackagesPackageModelToJSON,
} from './SiteLastPackagesPackageModel';

/**
 * 
 * @export
 * @interface SiteLastPackagesModel
 */
export interface SiteLastPackagesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SiteLastPackagesModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof SiteLastPackagesModel
     */
    length?: number;
    /**
     * last tasks packages information
     * @type {Array<SiteLastPackagesPackageModel>}
     * @memberof SiteLastPackagesModel
     */
    tasks?: Array<SiteLastPackagesPackageModel>;
    /**
     * last loaded branch task
     * @type {number}
     * @memberof SiteLastPackagesModel
     */
    lastBranchTask?: number;
    /**
     * last loaded branch date
     * @type {string}
     * @memberof SiteLastPackagesModel
     */
    lastBranchDate?: string;
}

/**
 * Check if a given object implements the SiteLastPackagesModel interface.
 */
export function instanceOfSiteLastPackagesModel(value: object): value is SiteLastPackagesModel {
    return true;
}

export function SiteLastPackagesModelFromJSON(json: any): SiteLastPackagesModel {
    return SiteLastPackagesModelFromJSONTyped(json, false);
}

export function SiteLastPackagesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteLastPackagesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(SiteLastPackagesPackageModelFromJSON)),
        'lastBranchTask': json['last_branch_task'] == null ? undefined : json['last_branch_task'],
        'lastBranchDate': json['last_branch_date'] == null ? undefined : json['last_branch_date'],
    };
}

export function SiteLastPackagesModelToJSON(value?: SiteLastPackagesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(SiteLastPackagesPackageModelToJSON)),
        'last_branch_task': value['lastBranchTask'],
        'last_branch_date': value['lastBranchDate'],
    };
}

