/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteBeehiveByMaintainerElementModel } from './SiteBeehiveByMaintainerElementModel';
import {
    SiteBeehiveByMaintainerElementModelFromJSON,
    SiteBeehiveByMaintainerElementModelFromJSONTyped,
    SiteBeehiveByMaintainerElementModelToJSON,
} from './SiteBeehiveByMaintainerElementModel';

/**
 * 
 * @export
 * @interface SiteBeehiveByMaintainerModel
 */
export interface SiteBeehiveByMaintainerModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SiteBeehiveByMaintainerModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof SiteBeehiveByMaintainerModel
     */
    length?: number;
    /**
     * Beehive packages rebuild errors
     * @type {Array<SiteBeehiveByMaintainerElementModel>}
     * @memberof SiteBeehiveByMaintainerModel
     */
    beehive?: Array<SiteBeehiveByMaintainerElementModel>;
}

/**
 * Check if a given object implements the SiteBeehiveByMaintainerModel interface.
 */
export function instanceOfSiteBeehiveByMaintainerModel(value: object): value is SiteBeehiveByMaintainerModel {
    return true;
}

export function SiteBeehiveByMaintainerModelFromJSON(json: any): SiteBeehiveByMaintainerModel {
    return SiteBeehiveByMaintainerModelFromJSONTyped(json, false);
}

export function SiteBeehiveByMaintainerModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteBeehiveByMaintainerModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'beehive': json['beehive'] == null ? undefined : ((json['beehive'] as Array<any>).map(SiteBeehiveByMaintainerElementModelFromJSON)),
    };
}

export function SiteBeehiveByMaintainerModelToJSON(value?: SiteBeehiveByMaintainerModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'beehive': value['beehive'] == null ? undefined : ((value['beehive'] as Array<any>).map(SiteBeehiveByMaintainerElementModelToJSON)),
    };
}

