/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SitePackageVersionsElementModel } from './SitePackageVersionsElementModel';
import {
    SitePackageVersionsElementModelFromJSON,
    SitePackageVersionsElementModelFromJSONTyped,
    SitePackageVersionsElementModelToJSON,
} from './SitePackageVersionsElementModel';
import type { SitePackagesBinaryListElementModel } from './SitePackagesBinaryListElementModel';
import {
    SitePackagesBinaryListElementModelFromJSON,
    SitePackagesBinaryListElementModelFromJSONTyped,
    SitePackagesBinaryListElementModelToJSON,
} from './SitePackagesBinaryListElementModel';

/**
 * 
 * @export
 * @interface SitePackagesBinaryListModel
 */
export interface SitePackagesBinaryListModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SitePackagesBinaryListModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof SitePackagesBinaryListModel
     */
    length?: number;
    /**
     * binary packages list
     * @type {Array<SitePackagesBinaryListElementModel>}
     * @memberof SitePackagesBinaryListModel
     */
    packages?: Array<SitePackagesBinaryListElementModel>;
    /**
     * all package versions
     * @type {Array<SitePackageVersionsElementModel>}
     * @memberof SitePackagesBinaryListModel
     */
    versions?: Array<SitePackageVersionsElementModel>;
}

/**
 * Check if a given object implements the SitePackagesBinaryListModel interface.
 */
export function instanceOfSitePackagesBinaryListModel(value: object): value is SitePackagesBinaryListModel {
    return true;
}

export function SitePackagesBinaryListModelFromJSON(json: any): SitePackagesBinaryListModel {
    return SitePackagesBinaryListModelFromJSONTyped(json, false);
}

export function SitePackagesBinaryListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitePackagesBinaryListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(SitePackagesBinaryListElementModelFromJSON)),
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(SitePackageVersionsElementModelFromJSON)),
    };
}

export function SitePackagesBinaryListModelToJSON(value?: SitePackagesBinaryListModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(SitePackagesBinaryListElementModelToJSON)),
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(SitePackageVersionsElementModelToJSON)),
    };
}

