/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SItePackagesVersionsFromTasksElementModel
 */
export interface SItePackagesVersionsFromTasksElementModel {
    /**
     * package set name
     * @type {string}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    branch?: string;
    /**
     * package build task
     * @type {number}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    task?: number;
    /**
     * package hash UInt64 as string
     * @type {string}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    hash?: string;
    /**
     * task owner nickname
     * @type {string}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    owner?: string;
    /**
     * task change date
     * @type {Date}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    changed?: Date;
    /**
     * package name
     * @type {string}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof SItePackagesVersionsFromTasksElementModel
     */
    release?: string;
}

/**
 * Check if a given object implements the SItePackagesVersionsFromTasksElementModel interface.
 */
export function instanceOfSItePackagesVersionsFromTasksElementModel(value: object): value is SItePackagesVersionsFromTasksElementModel {
    return true;
}

export function SItePackagesVersionsFromTasksElementModelFromJSON(json: any): SItePackagesVersionsFromTasksElementModel {
    return SItePackagesVersionsFromTasksElementModelFromJSONTyped(json, false);
}

export function SItePackagesVersionsFromTasksElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SItePackagesVersionsFromTasksElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'task': json['task'] == null ? undefined : json['task'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'changed': json['changed'] == null ? undefined : (new Date(json['changed'])),
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
    };
}

export function SItePackagesVersionsFromTasksElementModelToJSON(value?: SItePackagesVersionsFromTasksElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'branch': value['branch'],
        'task': value['task'],
        'hash': value['hash'],
        'owner': value['owner'],
        'changed': value['changed'] == null ? undefined : ((value['changed']).toISOString()),
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
    };
}

