/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteBriefPackageInfoModel
 */
export interface SiteBriefPackageInfoModel {
    /**
     * package name
     * @type {string}
     * @memberof SiteBriefPackageInfoModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof SiteBriefPackageInfoModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof SiteBriefPackageInfoModel
     */
    release?: string;
    /**
     * package arch
     * @type {string}
     * @memberof SiteBriefPackageInfoModel
     */
    arch?: string;
    /**
     * package summary
     * @type {string}
     * @memberof SiteBriefPackageInfoModel
     */
    summary?: string;
    /**
     * package type (source | binary)
     * @type {string}
     * @memberof SiteBriefPackageInfoModel
     */
    type?: string;
}

/**
 * Check if a given object implements the SiteBriefPackageInfoModel interface.
 */
export function instanceOfSiteBriefPackageInfoModel(value: object): value is SiteBriefPackageInfoModel {
    return true;
}

export function SiteBriefPackageInfoModelFromJSON(json: any): SiteBriefPackageInfoModel {
    return SiteBriefPackageInfoModelFromJSONTyped(json, false);
}

export function SiteBriefPackageInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteBriefPackageInfoModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'arch': json['arch'] == null ? undefined : json['arch'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SiteBriefPackageInfoModelToJSON(value?: SiteBriefPackageInfoModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'arch': value['arch'],
        'summary': value['summary'],
        'type': value['type'],
    };
}

