/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteBinPackageScriptsElementModel
 */
export interface SiteBinPackageScriptsElementModel {
    /**
     * pre install script
     * @type {string}
     * @memberof SiteBinPackageScriptsElementModel
     */
    prein?: string;
    /**
     * post install script
     * @type {string}
     * @memberof SiteBinPackageScriptsElementModel
     */
    postin?: string;
    /**
     * pre uninstall script
     * @type {string}
     * @memberof SiteBinPackageScriptsElementModel
     */
    preun?: string;
    /**
     * post uninstall script
     * @type {string}
     * @memberof SiteBinPackageScriptsElementModel
     */
    postun?: string;
    /**
     * pre transaction script
     * @type {string}
     * @memberof SiteBinPackageScriptsElementModel
     */
    pretrans?: string;
    /**
     * post transaction script
     * @type {string}
     * @memberof SiteBinPackageScriptsElementModel
     */
    posttrans?: string;
}

/**
 * Check if a given object implements the SiteBinPackageScriptsElementModel interface.
 */
export function instanceOfSiteBinPackageScriptsElementModel(value: object): value is SiteBinPackageScriptsElementModel {
    return true;
}

export function SiteBinPackageScriptsElementModelFromJSON(json: any): SiteBinPackageScriptsElementModel {
    return SiteBinPackageScriptsElementModelFromJSONTyped(json, false);
}

export function SiteBinPackageScriptsElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteBinPackageScriptsElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'prein': json['prein'] == null ? undefined : json['prein'],
        'postin': json['postin'] == null ? undefined : json['postin'],
        'preun': json['preun'] == null ? undefined : json['preun'],
        'postun': json['postun'] == null ? undefined : json['postun'],
        'pretrans': json['pretrans'] == null ? undefined : json['pretrans'],
        'posttrans': json['posttrans'] == null ? undefined : json['posttrans'],
    };
}

export function SiteBinPackageScriptsElementModelToJSON(value?: SiteBinPackageScriptsElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'prein': value['prein'],
        'postin': value['postin'],
        'preun': value['preun'],
        'postun': value['postun'],
        'pretrans': value['pretrans'],
        'posttrans': value['posttrans'],
    };
}

