/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteImageCategoryElementModel } from './SiteImageCategoryElementModel';
import {
    SiteImageCategoryElementModelFromJSON,
    SiteImageCategoryElementModelFromJSONTyped,
    SiteImageCategoryElementModelToJSON,
} from './SiteImageCategoryElementModel';

/**
 * 
 * @export
 * @interface SiteImageCategoriesModel
 */
export interface SiteImageCategoriesModel {
    /**
     * request arguments
     * @type {object}
     * @memberof SiteImageCategoriesModel
     */
    requestArgs?: object;
    /**
     * number of categories in list
     * @type {number}
     * @memberof SiteImageCategoriesModel
     */
    length?: number;
    /**
     * found categories
     * @type {Array<SiteImageCategoryElementModel>}
     * @memberof SiteImageCategoriesModel
     */
    categories?: Array<SiteImageCategoryElementModel>;
}

/**
 * Check if a given object implements the SiteImageCategoriesModel interface.
 */
export function instanceOfSiteImageCategoriesModel(value: object): value is SiteImageCategoriesModel {
    return true;
}

export function SiteImageCategoriesModelFromJSON(json: any): SiteImageCategoriesModel {
    return SiteImageCategoriesModelFromJSONTyped(json, false);
}

export function SiteImageCategoriesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteImageCategoriesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(SiteImageCategoryElementModelFromJSON)),
    };
}

export function SiteImageCategoriesModelToJSON(value?: SiteImageCategoriesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(SiteImageCategoryElementModelToJSON)),
    };
}

