/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteLastPackagesElementModel } from './SiteLastPackagesElementModel';
import {
    SiteLastPackagesElementModelFromJSON,
    SiteLastPackagesElementModelFromJSONTyped,
    SiteLastPackagesElementModelToJSON,
} from './SiteLastPackagesElementModel';

/**
 * 
 * @export
 * @interface SiteLastPackagesPackageModel
 */
export interface SiteLastPackagesPackageModel {
    /**
     * task id
     * @type {number}
     * @memberof SiteLastPackagesPackageModel
     */
    taskId?: number;
    /**
     * task owner
     * @type {string}
     * @memberof SiteLastPackagesPackageModel
     */
    taskOwner?: string;
    /**
     * task completed at
     * @type {string}
     * @memberof SiteLastPackagesPackageModel
     */
    taskChanged?: string;
    /**
     * task message
     * @type {string}
     * @memberof SiteLastPackagesPackageModel
     */
    taskMessage?: string;
    /**
     * task subtasks packages information
     * @type {Array<SiteLastPackagesElementModel>}
     * @memberof SiteLastPackagesPackageModel
     */
    packages?: Array<SiteLastPackagesElementModel>;
}

/**
 * Check if a given object implements the SiteLastPackagesPackageModel interface.
 */
export function instanceOfSiteLastPackagesPackageModel(value: object): value is SiteLastPackagesPackageModel {
    return true;
}

export function SiteLastPackagesPackageModelFromJSON(json: any): SiteLastPackagesPackageModel {
    return SiteLastPackagesPackageModelFromJSONTyped(json, false);
}

export function SiteLastPackagesPackageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteLastPackagesPackageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'taskOwner': json['task_owner'] == null ? undefined : json['task_owner'],
        'taskChanged': json['task_changed'] == null ? undefined : json['task_changed'],
        'taskMessage': json['task_message'] == null ? undefined : json['task_message'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(SiteLastPackagesElementModelFromJSON)),
    };
}

export function SiteLastPackagesPackageModelToJSON(value?: SiteLastPackagesPackageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task_id': value['taskId'],
        'task_owner': value['taskOwner'],
        'task_changed': value['taskChanged'],
        'task_message': value['taskMessage'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(SiteLastPackagesElementModelToJSON)),
    };
}

