/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteAllPackagesetsSummaryBranchesModel } from './SiteAllPackagesetsSummaryBranchesModel';
import {
    SiteAllPackagesetsSummaryBranchesModelFromJSON,
    SiteAllPackagesetsSummaryBranchesModelFromJSONTyped,
    SiteAllPackagesetsSummaryBranchesModelToJSON,
} from './SiteAllPackagesetsSummaryBranchesModel';

/**
 * 
 * @export
 * @interface SiteAllPackagesetsSummaryModel
 */
export interface SiteAllPackagesetsSummaryModel {
    /**
     * number of packages found
     * @type {number}
     * @memberof SiteAllPackagesetsSummaryModel
     */
    length?: number;
    /**
     * list of branches with source packages count
     * @type {Array<SiteAllPackagesetsSummaryBranchesModel>}
     * @memberof SiteAllPackagesetsSummaryModel
     */
    branches?: Array<SiteAllPackagesetsSummaryBranchesModel>;
}

/**
 * Check if a given object implements the SiteAllPackagesetsSummaryModel interface.
 */
export function instanceOfSiteAllPackagesetsSummaryModel(value: object): value is SiteAllPackagesetsSummaryModel {
    return true;
}

export function SiteAllPackagesetsSummaryModelFromJSON(json: any): SiteAllPackagesetsSummaryModel {
    return SiteAllPackagesetsSummaryModelFromJSONTyped(json, false);
}

export function SiteAllPackagesetsSummaryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteAllPackagesetsSummaryModel {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(SiteAllPackagesetsSummaryBranchesModelFromJSON)),
    };
}

export function SiteAllPackagesetsSummaryModelToJSON(value?: SiteAllPackagesetsSummaryModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(SiteAllPackagesetsSummaryBranchesModelToJSON)),
    };
}

