/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteAllPackagesetsSummaryBranchesModel } from './SiteAllPackagesetsSummaryBranchesModel';
import {
    SiteAllPackagesetsSummaryBranchesModelFromJSON,
    SiteAllPackagesetsSummaryBranchesModelFromJSONTyped,
    SiteAllPackagesetsSummaryBranchesModelToJSON,
} from './SiteAllPackagesetsSummaryBranchesModel';
import type { SitePackagesetStatusElementModel } from './SitePackagesetStatusElementModel';
import {
    SitePackagesetStatusElementModelFromJSON,
    SitePackagesetStatusElementModelFromJSONTyped,
    SitePackagesetStatusElementModelToJSON,
} from './SitePackagesetStatusElementModel';

/**
 * 
 * @export
 * @interface SitePackagesetsSummaryStatusModel
 */
export interface SitePackagesetsSummaryStatusModel {
    /**
     * number of packages found
     * @type {number}
     * @memberof SitePackagesetsSummaryStatusModel
     */
    length?: number;
    /**
     * list of branches with source packages count
     * @type {Array<SiteAllPackagesetsSummaryBranchesModel>}
     * @memberof SitePackagesetsSummaryStatusModel
     */
    branches?: Array<SiteAllPackagesetsSummaryBranchesModel>;
    /**
     * list of branches status
     * @type {Array<SitePackagesetStatusElementModel>}
     * @memberof SitePackagesetsSummaryStatusModel
     */
    status?: Array<SitePackagesetStatusElementModel>;
}

/**
 * Check if a given object implements the SitePackagesetsSummaryStatusModel interface.
 */
export function instanceOfSitePackagesetsSummaryStatusModel(value: object): value is SitePackagesetsSummaryStatusModel {
    return true;
}

export function SitePackagesetsSummaryStatusModelFromJSON(json: any): SitePackagesetsSummaryStatusModel {
    return SitePackagesetsSummaryStatusModelFromJSONTyped(json, false);
}

export function SitePackagesetsSummaryStatusModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitePackagesetsSummaryStatusModel {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'] == null ? undefined : json['length'],
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(SiteAllPackagesetsSummaryBranchesModelFromJSON)),
        'status': json['status'] == null ? undefined : ((json['status'] as Array<any>).map(SitePackagesetStatusElementModelFromJSON)),
    };
}

export function SitePackagesetsSummaryStatusModelToJSON(value?: SitePackagesetsSummaryStatusModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(SiteAllPackagesetsSummaryBranchesModelToJSON)),
        'status': value['status'] == null ? undefined : ((value['status'] as Array<any>).map(SitePackagesetStatusElementModelToJSON)),
    };
}

