/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitePackageDependenciesElementModel
 */
export interface SitePackageDependenciesElementModel {
    /**
     * the name of the dependent package
     * @type {string}
     * @memberof SitePackageDependenciesElementModel
     */
    name?: string;
    /**
     * the version of the dependent package
     * @type {string}
     * @memberof SitePackageDependenciesElementModel
     */
    version?: string;
    /**
     * dependency type
     * @type {string}
     * @memberof SitePackageDependenciesElementModel
     */
    type?: string;
    /**
     * dependency flag
     * @type {number}
     * @memberof SitePackageDependenciesElementModel
     */
    flag?: number;
    /**
     * decoded dependency flag
     * @type {Array<string>}
     * @memberof SitePackageDependenciesElementModel
     */
    flagDecoded?: Array<string>;
}

/**
 * Check if a given object implements the SitePackageDependenciesElementModel interface.
 */
export function instanceOfSitePackageDependenciesElementModel(value: object): value is SitePackageDependenciesElementModel {
    return true;
}

export function SitePackageDependenciesElementModelFromJSON(json: any): SitePackageDependenciesElementModel {
    return SitePackageDependenciesElementModelFromJSONTyped(json, false);
}

export function SitePackageDependenciesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitePackageDependenciesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'type': json['type'] == null ? undefined : json['type'],
        'flag': json['flag'] == null ? undefined : json['flag'],
        'flagDecoded': json['flag_decoded'] == null ? undefined : json['flag_decoded'],
    };
}

export function SitePackageDependenciesElementModelToJSON(value?: SitePackageDependenciesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'version': value['version'],
        'type': value['type'],
        'flag': value['flag'],
        'flag_decoded': value['flagDecoded'],
    };
}

