/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubTaskArchitectureModel
 */
export interface SubTaskArchitectureModel {
    /**
     * stage status
     * @type {string}
     * @memberof SubTaskArchitectureModel
     */
    stageStatus?: string;
    /**
     * subtask architecture
     * @type {string}
     * @memberof SubTaskArchitectureModel
     */
    arch?: string;
}

/**
 * Check if a given object implements the SubTaskArchitectureModel interface.
 */
export function instanceOfSubTaskArchitectureModel(value: object): value is SubTaskArchitectureModel {
    return true;
}

export function SubTaskArchitectureModelFromJSON(json: any): SubTaskArchitectureModel {
    return SubTaskArchitectureModelFromJSONTyped(json, false);
}

export function SubTaskArchitectureModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubTaskArchitectureModel {
    if (json == null) {
        return json;
    }
    return {
        
        'stageStatus': json['stage_status'] == null ? undefined : json['stage_status'],
        'arch': json['arch'] == null ? undefined : json['arch'],
    };
}

export function SubTaskArchitectureModelToJSON(value?: SubTaskArchitectureModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stage_status': value['stageStatus'],
        'arch': value['arch'],
    };
}

