/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubTasksElementModel } from './SubTasksElementModel';
import {
    SubTasksElementModelFromJSON,
    SubTasksElementModelFromJSONTyped,
    SubTasksElementModelToJSON,
} from './SubTasksElementModel';
import type { TaskApprovalElementModel } from './TaskApprovalElementModel';
import {
    TaskApprovalElementModelFromJSON,
    TaskApprovalElementModelFromJSONTyped,
    TaskApprovalElementModelToJSON,
} from './TaskApprovalElementModel';

/**
 * 
 * @export
 * @interface TasksListElementModel
 */
export interface TasksListElementModel {
    /**
     * task id
     * @type {number}
     * @memberof TasksListElementModel
     */
    taskId?: number;
    /**
     * repository name
     * @type {string}
     * @memberof TasksListElementModel
     */
    taskRepo?: string;
    /**
     * task state
     * @type {string}
     * @memberof TasksListElementModel
     */
    taskState?: string;
    /**
     * task owner
     * @type {string}
     * @memberof TasksListElementModel
     */
    taskOwner?: string;
    /**
     * task try number
     * @type {number}
     * @memberof TasksListElementModel
     */
    taskTry?: number;
    /**
     * task iteration number
     * @type {number}
     * @memberof TasksListElementModel
     */
    taskIter?: number;
    /**
     * task test only
     * @type {number}
     * @memberof TasksListElementModel
     */
    taskTestonly?: number;
    /**
     * task changed
     * @type {Date}
     * @memberof TasksListElementModel
     */
    taskChanged?: Date;
    /**
     * task message
     * @type {string}
     * @memberof TasksListElementModel
     */
    taskMessage?: string;
    /**
     * task stage
     * @type {string}
     * @memberof TasksListElementModel
     */
    taskStage?: string;
    /**
     * task dependencies
     * @type {Array<number>}
     * @memberof TasksListElementModel
     */
    dependencies?: Array<number>;
    /**
     * list of subtasks by task
     * @type {Array<SubTasksElementModel>}
     * @memberof TasksListElementModel
     */
    subtasks?: Array<SubTasksElementModel>;
    /**
     * list of approvals for task
     * @type {Array<TaskApprovalElementModel>}
     * @memberof TasksListElementModel
     */
    approval?: Array<TaskApprovalElementModel>;
}

/**
 * Check if a given object implements the TasksListElementModel interface.
 */
export function instanceOfTasksListElementModel(value: object): value is TasksListElementModel {
    return true;
}

export function TasksListElementModelFromJSON(json: any): TasksListElementModel {
    return TasksListElementModelFromJSONTyped(json, false);
}

export function TasksListElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksListElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'taskRepo': json['task_repo'] == null ? undefined : json['task_repo'],
        'taskState': json['task_state'] == null ? undefined : json['task_state'],
        'taskOwner': json['task_owner'] == null ? undefined : json['task_owner'],
        'taskTry': json['task_try'] == null ? undefined : json['task_try'],
        'taskIter': json['task_iter'] == null ? undefined : json['task_iter'],
        'taskTestonly': json['task_testonly'] == null ? undefined : json['task_testonly'],
        'taskChanged': json['task_changed'] == null ? undefined : (new Date(json['task_changed'])),
        'taskMessage': json['task_message'] == null ? undefined : json['task_message'],
        'taskStage': json['task_stage'] == null ? undefined : json['task_stage'],
        'dependencies': json['dependencies'] == null ? undefined : json['dependencies'],
        'subtasks': json['subtasks'] == null ? undefined : ((json['subtasks'] as Array<any>).map(SubTasksElementModelFromJSON)),
        'approval': json['approval'] == null ? undefined : ((json['approval'] as Array<any>).map(TaskApprovalElementModelFromJSON)),
    };
}

export function TasksListElementModelToJSON(value?: TasksListElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task_id': value['taskId'],
        'task_repo': value['taskRepo'],
        'task_state': value['taskState'],
        'task_owner': value['taskOwner'],
        'task_try': value['taskTry'],
        'task_iter': value['taskIter'],
        'task_testonly': value['taskTestonly'],
        'task_changed': value['taskChanged'] == null ? undefined : ((value['taskChanged']).toISOString()),
        'task_message': value['taskMessage'],
        'task_stage': value['taskStage'],
        'dependencies': value['dependencies'],
        'subtasks': value['subtasks'] == null ? undefined : ((value['subtasks'] as Array<any>).map(SubTasksElementModelToJSON)),
        'approval': value['approval'] == null ? undefined : ((value['approval'] as Array<any>).map(TaskApprovalElementModelToJSON)),
    };
}

