/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskApprovalElementModel
 */
export interface TaskApprovalElementModel {
    /**
     * approval type
     * @type {string}
     * @memberof TaskApprovalElementModel
     */
    type?: string;
    /**
     * maintainer nickname
     * @type {string}
     * @memberof TaskApprovalElementModel
     */
    nickname?: string;
    /**
     * approval message
     * @type {string}
     * @memberof TaskApprovalElementModel
     */
    message?: string;
}

/**
 * Check if a given object implements the TaskApprovalElementModel interface.
 */
export function instanceOfTaskApprovalElementModel(value: object): value is TaskApprovalElementModel {
    return true;
}

export function TaskApprovalElementModelFromJSON(json: any): TaskApprovalElementModel {
    return TaskApprovalElementModelFromJSONTyped(json, false);
}

export function TaskApprovalElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskApprovalElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function TaskApprovalElementModelToJSON(value?: TaskApprovalElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'nickname': value['nickname'],
        'message': value['message'],
    };
}

