/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskHistoryElementModel } from './TaskHistoryElementModel';
import {
    TaskHistoryElementModelFromJSON,
    TaskHistoryElementModelFromJSONTyped,
    TaskHistoryElementModelToJSON,
} from './TaskHistoryElementModel';

/**
 * 
 * @export
 * @interface TaskHistoryModel
 */
export interface TaskHistoryModel {
    /**
     * request arguments
     * @type {object}
     * @memberof TaskHistoryModel
     */
    requestArgs?: object;
    /**
     * number of packages found
     * @type {number}
     * @memberof TaskHistoryModel
     */
    length?: number;
    /**
     * build requirements packages information
     * @type {Array<TaskHistoryElementModel>}
     * @memberof TaskHistoryModel
     */
    tasks?: Array<TaskHistoryElementModel>;
}

/**
 * Check if a given object implements the TaskHistoryModel interface.
 */
export function instanceOfTaskHistoryModel(value: object): value is TaskHistoryModel {
    return true;
}

export function TaskHistoryModelFromJSON(json: any): TaskHistoryModel {
    return TaskHistoryModelFromJSONTyped(json, false);
}

export function TaskHistoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskHistoryModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'length': json['length'] == null ? undefined : json['length'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(TaskHistoryElementModelFromJSON)),
    };
}

export function TaskHistoryModelToJSON(value?: TaskHistoryModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request_args': value['requestArgs'],
        'length': value['length'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(TaskHistoryElementModelToJSON)),
    };
}

