/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskInfoArchsModel
 */
export interface TaskInfoArchsModel {
    /**
     * iteration state last changed
     * @type {string}
     * @memberof TaskInfoArchsModel
     */
    lastChanged?: string;
    /**
     * iteration arch
     * @type {string}
     * @memberof TaskInfoArchsModel
     */
    arch?: string;
    /**
     * iteration state
     * @type {string}
     * @memberof TaskInfoArchsModel
     */
    status?: string;
}

/**
 * Check if a given object implements the TaskInfoArchsModel interface.
 */
export function instanceOfTaskInfoArchsModel(value: object): value is TaskInfoArchsModel {
    return true;
}

export function TaskInfoArchsModelFromJSON(json: any): TaskInfoArchsModel {
    return TaskInfoArchsModelFromJSONTyped(json, false);
}

export function TaskInfoArchsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInfoArchsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'lastChanged': json['last_changed'] == null ? undefined : json['last_changed'],
        'arch': json['arch'] == null ? undefined : json['arch'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TaskInfoArchsModelToJSON(value?: TaskInfoArchsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'last_changed': value['lastChanged'],
        'arch': value['arch'],
        'status': value['status'],
    };
}

