/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskBuildDependencyElementModel
 */
export interface TaskBuildDependencyElementModel {
    /**
     * package dependenyc depth
     * @type {number}
     * @memberof TaskBuildDependencyElementModel
     */
    depth?: number;
    /**
     * package name
     * @type {string}
     * @memberof TaskBuildDependencyElementModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof TaskBuildDependencyElementModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof TaskBuildDependencyElementModel
     */
    release?: string;
    /**
     * package epoch
     * @type {number}
     * @memberof TaskBuildDependencyElementModel
     */
    epoch?: number;
    /**
     * package serial
     * @type {number}
     * @memberof TaskBuildDependencyElementModel
     */
    serial?: number;
    /**
     * source package file
     * @type {string}
     * @memberof TaskBuildDependencyElementModel
     */
    sourcerpm?: string;
    /**
     * package set name
     * @type {string}
     * @memberof TaskBuildDependencyElementModel
     */
    branch?: string;
    /**
     * package build time
     * @type {string}
     * @memberof TaskBuildDependencyElementModel
     */
    buildtime?: string;
    /**
     * package archs
     * @type {Array<string>}
     * @memberof TaskBuildDependencyElementModel
     */
    archs?: Array<string>;
    /**
     * package cycle dependencies
     * @type {Array<string>}
     * @memberof TaskBuildDependencyElementModel
     */
    cycle?: Array<string>;
    /**
     * package requirements
     * @type {Array<string>}
     * @memberof TaskBuildDependencyElementModel
     */
    requires?: Array<string>;
    /**
     * package ACL list
     * @type {Array<string>}
     * @memberof TaskBuildDependencyElementModel
     */
    acl?: Array<string>;
}

/**
 * Check if a given object implements the TaskBuildDependencyElementModel interface.
 */
export function instanceOfTaskBuildDependencyElementModel(value: object): value is TaskBuildDependencyElementModel {
    return true;
}

export function TaskBuildDependencyElementModelFromJSON(json: any): TaskBuildDependencyElementModel {
    return TaskBuildDependencyElementModelFromJSONTyped(json, false);
}

export function TaskBuildDependencyElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskBuildDependencyElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'depth': json['depth'] == null ? undefined : json['depth'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'serial': json['serial'] == null ? undefined : json['serial'],
        'sourcerpm': json['sourcerpm'] == null ? undefined : json['sourcerpm'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'buildtime': json['buildtime'] == null ? undefined : json['buildtime'],
        'archs': json['archs'] == null ? undefined : json['archs'],
        'cycle': json['cycle'] == null ? undefined : json['cycle'],
        'requires': json['requires'] == null ? undefined : json['requires'],
        'acl': json['acl'] == null ? undefined : json['acl'],
    };
}

export function TaskBuildDependencyElementModelToJSON(value?: TaskBuildDependencyElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'depth': value['depth'],
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'epoch': value['epoch'],
        'serial': value['serial'],
        'sourcerpm': value['sourcerpm'],
        'branch': value['branch'],
        'buildtime': value['buildtime'],
        'archs': value['archs'],
        'cycle': value['cycle'],
        'requires': value['requires'],
        'acl': value['acl'],
    };
}

