/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskDiffPackagesModel } from './TaskDiffPackagesModel';
import {
    TaskDiffPackagesModelFromJSON,
    TaskDiffPackagesModelFromJSONTyped,
    TaskDiffPackagesModelToJSON,
} from './TaskDiffPackagesModel';

/**
 * 
 * @export
 * @interface TaskDiffArchsModel
 */
export interface TaskDiffArchsModel {
    /**
     * 
     * @type {string}
     * @memberof TaskDiffArchsModel
     */
    arch?: string;
    /**
     * 
     * @type {Array<TaskDiffPackagesModel>}
     * @memberof TaskDiffArchsModel
     */
    packages?: Array<TaskDiffPackagesModel>;
}

/**
 * Check if a given object implements the TaskDiffArchsModel interface.
 */
export function instanceOfTaskDiffArchsModel(value: object): value is TaskDiffArchsModel {
    return true;
}

export function TaskDiffArchsModelFromJSON(json: any): TaskDiffArchsModel {
    return TaskDiffArchsModelFromJSONTyped(json, false);
}

export function TaskDiffArchsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDiffArchsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'arch': json['arch'] == null ? undefined : json['arch'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(TaskDiffPackagesModelFromJSON)),
    };
}

export function TaskDiffArchsModelToJSON(value?: TaskDiffArchsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'arch': value['arch'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(TaskDiffPackagesModelToJSON)),
    };
}

