/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskRepoPackageModel
 */
export interface TaskRepoPackageModel {
    /**
     * package name
     * @type {string}
     * @memberof TaskRepoPackageModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof TaskRepoPackageModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof TaskRepoPackageModel
     */
    release?: string;
    /**
     * package file name
     * @type {string}
     * @memberof TaskRepoPackageModel
     */
    filename?: string;
}

/**
 * Check if a given object implements the TaskRepoPackageModel interface.
 */
export function instanceOfTaskRepoPackageModel(value: object): value is TaskRepoPackageModel {
    return true;
}

export function TaskRepoPackageModelFromJSON(json: any): TaskRepoPackageModel {
    return TaskRepoPackageModelFromJSONTyped(json, false);
}

export function TaskRepoPackageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskRepoPackageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'filename': json['filename'] == null ? undefined : json['filename'],
    };
}

export function TaskRepoPackageModelToJSON(value?: TaskRepoPackageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'filename': value['filename'],
    };
}

