/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskInfoApprovalsModel
 */
export interface TaskInfoApprovalsModel {
    /**
     * approval date
     * @type {string}
     * @memberof TaskInfoApprovalsModel
     */
    date?: string;
    /**
     * approval type
     * @type {string}
     * @memberof TaskInfoApprovalsModel
     */
    type?: string;
    /**
     * approver name
     * @type {string}
     * @memberof TaskInfoApprovalsModel
     */
    name?: string;
    /**
     * approval message
     * @type {string}
     * @memberof TaskInfoApprovalsModel
     */
    message?: string;
}

/**
 * Check if a given object implements the TaskInfoApprovalsModel interface.
 */
export function instanceOfTaskInfoApprovalsModel(value: object): value is TaskInfoApprovalsModel {
    return true;
}

export function TaskInfoApprovalsModelFromJSON(json: any): TaskInfoApprovalsModel {
    return TaskInfoApprovalsModelFromJSONTyped(json, false);
}

export function TaskInfoApprovalsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInfoApprovalsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function TaskInfoApprovalsModelToJSON(value?: TaskInfoApprovalsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'],
        'type': value['type'],
        'name': value['name'],
        'message': value['message'],
    };
}

