/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskDiffDependenciesModel } from './TaskDiffDependenciesModel';
import {
    TaskDiffDependenciesModelFromJSON,
    TaskDiffDependenciesModelFromJSONTyped,
    TaskDiffDependenciesModelToJSON,
} from './TaskDiffDependenciesModel';

/**
 * 
 * @export
 * @interface TaskDiffPackagesModel
 */
export interface TaskDiffPackagesModel {
    /**
     * 
     * @type {string}
     * @memberof TaskDiffPackagesModel
     */
    _package?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskDiffPackagesModel
     */
    del?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskDiffPackagesModel
     */
    add?: Array<string>;
    /**
     * 
     * @type {Array<TaskDiffDependenciesModel>}
     * @memberof TaskDiffPackagesModel
     */
    dependencies?: Array<TaskDiffDependenciesModel>;
}

/**
 * Check if a given object implements the TaskDiffPackagesModel interface.
 */
export function instanceOfTaskDiffPackagesModel(value: object): value is TaskDiffPackagesModel {
    return true;
}

export function TaskDiffPackagesModelFromJSON(json: any): TaskDiffPackagesModel {
    return TaskDiffPackagesModelFromJSONTyped(json, false);
}

export function TaskDiffPackagesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDiffPackagesModel {
    if (json == null) {
        return json;
    }
    return {
        
        '_package': json['package'] == null ? undefined : json['package'],
        'del': json['del'] == null ? undefined : json['del'],
        'add': json['add'] == null ? undefined : json['add'],
        'dependencies': json['dependencies'] == null ? undefined : ((json['dependencies'] as Array<any>).map(TaskDiffDependenciesModelFromJSON)),
    };
}

export function TaskDiffPackagesModelToJSON(value?: TaskDiffPackagesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'package': value['_package'],
        'del': value['del'],
        'add': value['add'],
        'dependencies': value['dependencies'] == null ? undefined : ((value['dependencies'] as Array<any>).map(TaskDiffDependenciesModelToJSON)),
    };
}

