/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskFindPackagesetElementModel } from './TaskFindPackagesetElementModel';
import {
    TaskFindPackagesetElementModelFromJSON,
    TaskFindPackagesetElementModelFromJSONTyped,
    TaskFindPackagesetElementModelToJSON,
} from './TaskFindPackagesetElementModel';

/**
 * 
 * @export
 * @interface TaskFindPackagesetModel
 */
export interface TaskFindPackagesetModel {
    /**
     * task id
     * @type {number}
     * @memberof TaskFindPackagesetModel
     */
    id?: number;
    /**
     * request arguments
     * @type {object}
     * @memberof TaskFindPackagesetModel
     */
    requestArgs?: object;
    /**
     * request arguments
     * @type {Array<string>}
     * @memberof TaskFindPackagesetModel
     */
    taskPackages?: Array<string>;
    /**
     * number of packages found
     * @type {number}
     * @memberof TaskFindPackagesetModel
     */
    length?: number;
    /**
     * package set packages information
     * @type {Array<TaskFindPackagesetElementModel>}
     * @memberof TaskFindPackagesetModel
     */
    packages?: Array<TaskFindPackagesetElementModel>;
}

/**
 * Check if a given object implements the TaskFindPackagesetModel interface.
 */
export function instanceOfTaskFindPackagesetModel(value: object): value is TaskFindPackagesetModel {
    return true;
}

export function TaskFindPackagesetModelFromJSON(json: any): TaskFindPackagesetModel {
    return TaskFindPackagesetModelFromJSONTyped(json, false);
}

export function TaskFindPackagesetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskFindPackagesetModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'requestArgs': json['request_args'] == null ? undefined : json['request_args'],
        'taskPackages': json['task_packages'] == null ? undefined : json['task_packages'],
        'length': json['length'] == null ? undefined : json['length'],
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(TaskFindPackagesetElementModelFromJSON)),
    };
}

export function TaskFindPackagesetModelToJSON(value?: TaskFindPackagesetModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'request_args': value['requestArgs'],
        'task_packages': value['taskPackages'],
        'length': value['length'],
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(TaskFindPackagesetElementModelToJSON)),
    };
}

