/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskInfoPackageModel
 */
export interface TaskInfoPackageModel {
    /**
     * package name
     * @type {string}
     * @memberof TaskInfoPackageModel
     */
    name?: string;
    /**
     * package version
     * @type {string}
     * @memberof TaskInfoPackageModel
     */
    version?: string;
    /**
     * package release
     * @type {string}
     * @memberof TaskInfoPackageModel
     */
    release?: string;
    /**
     * package file name
     * @type {string}
     * @memberof TaskInfoPackageModel
     */
    filename?: string;
}

/**
 * Check if a given object implements the TaskInfoPackageModel interface.
 */
export function instanceOfTaskInfoPackageModel(value: object): value is TaskInfoPackageModel {
    return true;
}

export function TaskInfoPackageModelFromJSON(json: any): TaskInfoPackageModel {
    return TaskInfoPackageModelFromJSONTyped(json, false);
}

export function TaskInfoPackageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInfoPackageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'release': json['release'] == null ? undefined : json['release'],
        'filename': json['filename'] == null ? undefined : json['filename'],
    };
}

export function TaskInfoPackageModelToJSON(value?: TaskInfoPackageModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'version': value['version'],
        'release': value['release'],
        'filename': value['filename'],
    };
}

