/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskInfoPackageModel } from './TaskInfoPackageModel';
import {
    TaskInfoPackageModelFromJSON,
    TaskInfoPackageModelFromJSONTyped,
    TaskInfoPackageModelToJSON,
} from './TaskInfoPackageModel';

/**
 * 
 * @export
 * @interface TaskInfoPlanModel
 */
export interface TaskInfoPlanModel {
    /**
     * source packages
     * @type {Array<TaskInfoPackageModel>}
     * @memberof TaskInfoPlanModel
     */
    src?: Array<TaskInfoPackageModel>;
    /**
     * binary packages
     * @type {Array<TaskInfoPackageModel>}
     * @memberof TaskInfoPlanModel
     */
    bin?: Array<TaskInfoPackageModel>;
}

/**
 * Check if a given object implements the TaskInfoPlanModel interface.
 */
export function instanceOfTaskInfoPlanModel(value: object): value is TaskInfoPlanModel {
    return true;
}

export function TaskInfoPlanModelFromJSON(json: any): TaskInfoPlanModel {
    return TaskInfoPlanModelFromJSONTyped(json, false);
}

export function TaskInfoPlanModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInfoPlanModel {
    if (json == null) {
        return json;
    }
    return {
        
        'src': json['src'] == null ? undefined : ((json['src'] as Array<any>).map(TaskInfoPackageModelFromJSON)),
        'bin': json['bin'] == null ? undefined : ((json['bin'] as Array<any>).map(TaskInfoPackageModelFromJSON)),
    };
}

export function TaskInfoPlanModelToJSON(value?: TaskInfoPlanModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'src': value['src'] == null ? undefined : ((value['src'] as Array<any>).map(TaskInfoPackageModelToJSON)),
        'bin': value['bin'] == null ? undefined : ((value['bin'] as Array<any>).map(TaskInfoPackageModelToJSON)),
    };
}

