/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskIterationsElementModel
 */
export interface TaskIterationsElementModel {
    /**
     * task try number
     * @type {number}
     * @memberof TaskIterationsElementModel
     */
    taskTry?: number;
    /**
     * task iteration number
     * @type {number}
     * @memberof TaskIterationsElementModel
     */
    taskIter?: number;
}

/**
 * Check if a given object implements the TaskIterationsElementModel interface.
 */
export function instanceOfTaskIterationsElementModel(value: object): value is TaskIterationsElementModel {
    return true;
}

export function TaskIterationsElementModelFromJSON(json: any): TaskIterationsElementModel {
    return TaskIterationsElementModelFromJSONTyped(json, false);
}

export function TaskIterationsElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskIterationsElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'taskTry': json['task_try'] == null ? undefined : json['task_try'],
        'taskIter': json['task_iter'] == null ? undefined : json['task_iter'],
    };
}

export function TaskIterationsElementModelToJSON(value?: TaskIterationsElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task_try': value['taskTry'],
        'task_iter': value['taskIter'],
    };
}

