/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskDiffDependenciesModel
 */
export interface TaskDiffDependenciesModel {
    /**
     * 
     * @type {string}
     * @memberof TaskDiffDependenciesModel
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskDiffDependenciesModel
     */
    del?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskDiffDependenciesModel
     */
    add?: Array<string>;
}

/**
 * Check if a given object implements the TaskDiffDependenciesModel interface.
 */
export function instanceOfTaskDiffDependenciesModel(value: object): value is TaskDiffDependenciesModel {
    return true;
}

export function TaskDiffDependenciesModelFromJSON(json: any): TaskDiffDependenciesModel {
    return TaskDiffDependenciesModelFromJSONTyped(json, false);
}

export function TaskDiffDependenciesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDiffDependenciesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'del': json['del'] == null ? undefined : json['del'],
        'add': json['add'] == null ? undefined : json['add'],
    };
}

export function TaskDiffDependenciesModelToJSON(value?: TaskDiffDependenciesModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'del': value['del'],
        'add': value['add'],
    };
}

