/* tslint:disable */
/* eslint-disable */
/**
 * ALTRepo API
 * altrepo API v1
 *
 * The version of the OpenAPI document: 1.19.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VulnerabilitiesElementModel
 */
export interface VulnerabilitiesElementModel {
    /**
     * vulnerability id
     * @type {string}
     * @memberof VulnerabilitiesElementModel
     */
    id?: string;
    /**
     * vulnerability type
     * @type {string}
     * @memberof VulnerabilitiesElementModel
     */
    type?: string;
}

/**
 * Check if a given object implements the VulnerabilitiesElementModel interface.
 */
export function instanceOfVulnerabilitiesElementModel(value: object): value is VulnerabilitiesElementModel {
    return true;
}

export function VulnerabilitiesElementModelFromJSON(json: any): VulnerabilitiesElementModel {
    return VulnerabilitiesElementModelFromJSONTyped(json, false);
}

export function VulnerabilitiesElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VulnerabilitiesElementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function VulnerabilitiesElementModelToJSON(value?: VulnerabilitiesElementModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

